### PR TITLE
Implemented S3 Account-level public access block.

### PR DESCRIPTION
**Pull request by mikegrima**
- Also added AWS Config listing and fetching support

### CODE REVIEW

**Comment by mikegrima** [comment]
This also fixes the broken AWS Lambda test.

**Comment by mikegrima** [comment]
I see that tests are failing because `coverage` was upgraded to 5.0. For some reason, my pinning to version `4.5.4` isn't working so I am going to investigate why.

**Comment by mikegrima** [comment]
Found the issue -- updating.

**Comment by spulec** [comment]
Looks great! Thanks for all of this.

**Pull request merged**
