### PR TITLE
Raise InvalidGroup.NotFound in DescribeSecurityGroups

### PR DESCRIPTION
**Pull request by nuwang**
This PR fixes an issue where DescribeSecurityGroups does not raise an InvalidSecurityGroup exception when invalid ids/names are supplied, returning an empty list instead. Also fixes the same for snapshots, volumes, vpcs and subnets.

### CODE REVIEW

**Comment by nuwang** [comment]
I've found a few more places where the appropriate error is not being raised. I'll update the pull request to include these too.

**Comment by nuwang** [comment]
Fixed in commits: https://github.com/spulec/moto/pull/1157/commits/08c4eff0b26518cf14c7eacaa1eb060bfc17ea50 and: https://github.com/spulec/moto/pull/1157/commits/ca56955a97c98057bffb7b3b9bba9f49fd8212bf

**Comment by JackDanger** [comment]
This is really great!

**Comment by JackDanger** [comment]
This is now released as part of Moto 1.1.11

**Comment by nuwang** [comment]
That's great! Thanks again for the super fast response.

**Pull request merged**
