### PR TITLE
feat: link instance profile with ec2 instance

### PR DESCRIPTION
**Pull request by rafcio19**
Improvement on https://github.com/spulec/moto/pull/3064

Links up IAM instance profile with the ec2 backend.

### CODE REVIEW

**Comment by rafcio19** [comment]
Hey @bblommers, could you rerun the [failing Unit tests in Server Mode (3.6) job ](https://github.com/spulec/moto/actions/runs/3346472400/jobs/5543521741#step:9:6684)? Seems like a fluke, everything else passes 🤞 🤔

**Comment by rafcio19** [comment]
That _ Unit tests in Server Mode (3.6)_ job passes now so I think this is ready to be reviewed.

**Comment by bblommers** [comment]
Hi @rafcio19, thanks for the PR! 

The Terraform tests are still failing with this error:
`Error: error setting iam_instance_profile: error parsing ARN (): arn: invalid prefix`
Which is due to the fact that the ARN is now empty when no instance profile is provided.

It should be OK if we change this to only output this part of the XML if the instance profile exists:
```
{% if instance.iam_instance_profile %}
          <iamInstanceProfile>
            <arn>{{ instance.iam_instance_profile['Arn'] }}</arn>
            <id>{{ instance.iam_instance_profile['Id'] }}</id>
          </iamInstanceProfile>
{% endif %}
```
That should fix all the tests - happy to merge once they pass.

**Review by bblommers — APPROVED** [review]
LGTM - thanks for the PR @rafcio19!

**Pull request merged**
