### PR TITLE
add support for ECS desiredCount mocking

### PR DESCRIPTION
**Pull request by thehesiod**
This adds a 10s delay between setting desiredCount, and it being reflected in runningCount

### CODE REVIEW

**Comment by thehesiod** [comment]
let me know what you guys think of the pendingCount changes in the unittests. Also the tests can be sped up by mocking of threading.Timer...let me know if you guys want me do that

**Comment by terrycain** [comment]
You could mock threading.Timer but that wouldn't work when moto is running in server mode would it?

**Comment by thehesiod** [comment]
Perhaps tests only run outside server mode?

**Comment by spulec** [comment]
Should we have a more general idea how we want to solve https://github.com/spulec/moto/issues/380 and https://github.com/spulec/moto/issues/192? It seems like this issue will come up for many services.

**Comment by thehesiod** [comment]
I think the general solution I think could build on this, by defining the timeout periods, etc

**Comment by spulec** [comment]
As a first step, it would be great to agree on our philosophy for this. I think we will need it for the docs anyway.

How does moto think of state changes? Are they immediate or delayed? If delayed, can the user choose a timeframe for the change or can they make it immediate?

Freezegun has this concept of [ticking forward time](https://github.com/spulec/freezegun#manual-ticks). Should we be providing something similar for state?

Apologies for blocking this very helpful work on a broader conversation, but I think these questions are fundamental and this will be very helpful across all of Moto.

My initial thoughts: I like state changes not being immediate by default, but the ability for users to globally configure how long a state change should take (including the option of setting that delay at zero). Alternatively, I also like the idea of a user being able to tick forward state like Freezegun.

cc @JackDanger @mikegrima in case they might have opinions too

**Comment by mikegrima** [comment]
I think I would need more context. 

However, I am generally against adding threading, timing delays, and other complex logic to moto. I agree with @spulec in this comment: https://github.com/spulec/moto/issues/380#issuecomment-123932483 -- if you have a need to do more special logic, then mock out the backend interface for your testing -- which is generally simple to do with pytest fixtures. In fact, I generally do with with IAM, which has a constant AWS account ID that is used to formulate the ARN -- I simply mock this value to the AWS account ID I am expecting.

It's very difficult to predict how users will expect their tests to operate, and I would prefer if we simply represent the data structure that AWS would be expected to return. Of course, you are then free to make whatever complex mocking logic you would like on your end to adjust the backend data for the test that you are looking to run.

**Comment by castrapel** [comment]
What is the specific use case for this timeout?

If it's a common one, I'd feel comfortable if the default behavior is simply returning the expected response (current behavior), but allowing configurable options for enhanced behavior doesn't hurt.

**Comment by thehesiod** [comment]
it sounds like for my simple test perhaps to avoid the timeouts I'd have to do the whole work on actually supporting bringing some form of simple docker-based ECS clusters up/down.  That would solve my particular use case.

The timeouts in this particular case are to support the different task states: `pending, desired, and running` counts to ensure I test these three codepaths.

**Comment by thehesiod** [comment]
Freezegun idea is interesting, for me this would need to be supported in server mode. Also the botocore events model is interesting, where you could get called back to dynamically set the timeouts.

**Comment by spulec** [comment]
Yeah, I like the freezegun idea. We could add an endpoint for moto-core for server mode similar to the [reset one](https://github.com/spulec/moto/blob/master/moto/core/urls.py#L13).

I'm not sure what you mean with the botocore events model. Can you explain that more?

**Comment by thehesiod** [comment]
See https://botocore.amazonaws.com/v1/documentation/api/latest/topics/events.html. Basically you can register for various events to either observe or modify behavior

**Comment by thehesiod** [comment]
So perhaps could create events like `before-transition.ecs.task.mode` or something

**Comment by spulec** [comment]
It seems like a thread-based approach probably isn't our best option, so going to close this for now and copy the ideas here over to #192.

**Pull request closed without merging**
