### PR TITLE
Adds cognito-idp sign_up endpoint.

### PR DESCRIPTION
**Pull request by dpretty**
Adds cognito-idp sign_up endpoint. Related issue: #2150

### CODE REVIEW

**Comment by terrycain** [comment]
Looks good to me, fix conficts and tests and your good.

**Comment by terrycain** [comment]
```

======================================================================
ERROR: test_cognitoidp.test_sign_up
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/spulec/moto/moto/core/models.py", line 80, in wrapper
    result = func(*args, **kwargs)
  File "/home/travis/build/spulec/moto/tests/test_cognitoidp/test_cognitoidp.py", line 1227, in test_sign_up
    result = conn.sign_up(ClientId=client_id, Username=username, Password=password)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the SignUp operation: 1696b73c-7497-4391-9163-8210437a8b7d
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost:5000
urllib3.connectionpool: DEBUG: http://localhost:5000 "POST /moto-api/reset HTTP/1.1" 200 16
urllib3.util.retry: DEBUG: Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost:5000
urllib3.connectionpool: DEBUG: http://localhost:5000 "POST / HTTP/1.1" 200 246
urllib3.util.retry: DEBUG: Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
urllib3.connectionpool: DEBUG: Resetting dropped connection: localhost
urllib3.connectionpool: DEBUG: http://localhost:5000 "POST / HTTP/1.1" 200 186
urllib3.util.retry: DEBUG: Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
urllib3.connectionpool: DEBUG: Resetting dropped connection: localhost
urllib3.connectionpool: DEBUG: http://localhost:5000 "POST / HTTP/1.1" 400 90
--------------------- >> end captured logging << ---------------------

Name                                                   Stmts   Miss  Cover
```
Fix this test in server mode

**Comment by griffinb** [comment]
Any plans to merge this?

**Comment by bblommers** [comment]
This functionality has been implemented by #3260

**Pull request closed without merging**
