### PR TITLE
#1514 Stackset Support

### PR DESCRIPTION
**Pull request by corrjo**
Added most of the stackset methods except for a few of the stack_set_operation ones. I'll probably have a follow up PR with those if I get a chance.

### CODE REVIEW

**Comment by corrjo** [comment]
Added the last few stack set operation methods. @spulec let me know if it needs anything else!

**Comment by corrjo** [comment]
Hey @spulec is there any chance we can get this into the next release?

**Comment by h1f1x** [comment]
Is there any status update on that?

**Comment by corrjo** [comment]
Not that I've heard. I ended up vendoring moto for now. looking forward to moving back to mainline when I can :)

**Comment by spulec** [comment]
Looks great! Thanks!

**Pull request merged**
