### PR TITLE
Add Python 3.7 support, remove Python 3.3 support

### PR DESCRIPTION
**Pull request by jonafato**
As of #1733, Python 3.7 is supported, so reflect that in the Trove
classifiers.

As of 2017-09-29, Python 3.3 is end-of-life and no longer receives
updates of any kind (including security fixes), so remove it from the
list of supported versions.

### CODE REVIEW

**Comment by jonafato** [comment]
@spulec I mistakenly removed something required for 2.7 support. I've added that back in and rebased against master, so I expect everything to pass now.

**Comment by mikegrima** [comment]
@spulec Any issues merging this? We're using 3.7 internally with without moto issues.

**Comment by dargueta** [comment]
While you're at it here, you could add `python_requires` to the `setuptools.setup()` call to make this package unavailable to unsupported Python versions. It won't even show up in `pip search`. I don't think the classifiers are obeyed by `pip`.

Unfortunately because you have to skip over 3.0-3.3, it's a little ugly:

```py
setup(
    ...
    python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*'
)
```

**Comment by terrycain** [comment]
I second adding python_requires,

**Comment by spulec** [comment]
Thanks!

**Pull request merged**
