### PR TITLE
Check SQS message size

### PR DESCRIPTION
**Pull request by iandees**
Fixes https://github.com/spulec/moto/issues/450

### CODE REVIEW

**Comment by spulec** [comment]
Awesome. Would you mind adding a small test?

**Comment by iandees** [comment]
Definitely!

**Comment by thedrow** [comment]
SQS now supports large messages by storing them in S3.
See https://aws.amazon.com/about-aws/whats-new/2015/10/now-send-payloads-up-to-2gb-with-amazon-sqs/
I think that only boto3 supports that but I'm not 100% sure since I'm not using boto3.

**Comment by iandees** [comment]
Wow, thanks for pointing this out. I added this because I was implementing that in boto :smile:.

**Comment by iandees** [comment]
@spulec Test added and it's passing.

**Comment by spulec** [comment]
Great, thanks for your work!

**Comment by iandees** [comment]
I don't suppose you could cut a new tag/release for this? :smile:

**Comment by spulec** [comment]
Just pushed moto 0.4.19

**Pull request merged**
