### PR TITLE
Fixed S3 lifecycle error message.

### LINKED ISSUE #1109: S3 GetBucketLifecycleConfiguration does not return proper error
AWS's API returns an HTTP 404 if an S3 bucket does not contain a lifecycle configuration. The error message returned by the API is a `NoSuchLifecycleConfiguration`.  However, it needs to be returned as an XML object as defined here: http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html.

In https://github.com/spulec/moto/blob/master/moto/s3/responses.py#L191, because this is not an XML string, `botocore` will not properly pass down the `NoSuchLifecycleConfiguration` error.

I am going to submit a PR to resolve this to be consistent with the AWS API (mostly going to copypasta the `S3_NO_POLICY` response).

### PR DESCRIPTION
**Pull request by mikegrima**
Fixes #1109 

Tested internally and works properly.

### CODE REVIEW

**Comment by mikegrima** [comment]
While I'm at it...I'm also adding in the `put_bucket_tagging` functionality in.

**Comment by mikegrima** [comment]
Added `put_bucket_tagging`... There are a bunch of other API calls that are missing.

I guess I should just add them all in.  @spulec Would you be able to quickly merge and push to PyPI once I'm done? I'm working on major S3 related things that we intend on open sourcing, and extensively using moto for my tests.  The only other way for me to continue is to mock out all of the S3 related calls and skip moto.

**Comment by mikegrima** [comment]
Added CORS support.

**Comment by JackDanger** [comment]
This is awesome, @mikegrima! I'll release a new version of Moto immediately with your fixes

**Pull request merged**
