### PR TITLE
Fix : Remove Invalid request error when response-template is not specified

### PR DESCRIPTION
**Pull request by usmangani1**
Fix : Remove Invalid request error when response-template is not specified

https://github.com/localstack/localstack/issues/3936

### CODE REVIEW

**Comment by bblommers** [comment]
This is a valid error @usmangani1 - this is exactly how AWS behaves. If you comment out the decorator and run that same test  you'll notice that AWS returns the same error

**Comment by usmangani1** [comment]
@bblommers I have tried the same thing against the AWS using the commands given below. AWS does not throw this error.


`service % aws  apigateway create-rest-api --name "TEST"
{
    "id": "ki5uhiune6",
    "name": "TEST",
    "createdDate": "2021-04-29T20:37:00+05:30",
    "apiKeySource": "HEADER",
    "endpointConfiguration": {
        "types": [
            "EDGE"
        ]
    },
    "disableExecuteApiEndpoint": false
}
service % aws  apigateway get-resources --rest-api-id ki5uhiune6  
{
    "items": [
        {
            "id": "giift4z7kg",
            "path": "/"
        }
    ]
}

service % aws apigateway create-resource --rest-api-id ki5uhiune6 --parent-id giift4z7kg --path-part pets
{
    "id": "g5atc8",
    "parentId": "giift4z7kg",
    "pathPart": "pets",
    "path": "/pets"
}
service % aws apigateway put-method --rest-api-id ki5uhiune6 --resource-id g5atc8 --http-method GET \
       --authorization-type "NONE"
{
    "httpMethod": "GET",
    "authorizationType": "NONE",
    "apiKeyRequired": false
}

service % aws apigateway put-method-response --rest-api-id ki5uhiune6 --resource-id g5atc8 --http-method GET \
       --status-code 200
{
    "statusCode": "200"
}
service % aws apigateway put-integration --rest-api-id ki5uhiune6 --resource-id g5atc8 --http-method GET --type HTTP \
       --integration-http-method GET \
       --uri 'http://petstore-demo-endpoint.execute-api.com/petstore/pets'
{
    "type": "HTTP",
    "httpMethod": "GET",
    "uri": "http://petstore-demo-endpoint.execute-api.com/petstore/pets",
    "connectionType": "INTERNET",
    "passthroughBehavior": "WHEN_NO_MATCH",
    "timeoutInMillis": 29000,
    "cacheNamespace": "g5atc8",
    "cacheKeyParameters": []
}
service % aws apigateway put-integration-response --rest-api-id ki5uhiune6 --resource-id g5atc8 --http-method GET  --status-code 200 --selection-pattern ""
{
    "statusCode": "200",
    "selectionPattern": ""
}
`

**Comment by bblommers** [comment]
Apologies @usmangani1 - I closed it prematurely.
After some more testing, the error seems to be thrown when the PUT request does not have a body at all. 

The existing unit test does not have any body parameters, so that should fail.
But: in the above example, the 'selection-pattern'-parameter is send over as the body, which is why it doesn't fail against AWS.

I'd be happy with moving this error scenario to `responses.py:integration_responses`. If the method == PUT and the body is empty, throw that `InvalidRequestInput`-exception. 
That way, the existing unit test (`test_put_integration_response_requires_responseTemplate`) should not need any modifications.

**Review by bblommers — CHANGES_REQUESTED** [review]
Thanks for making that change @usmangani1 - happy to merge once the build passes

**Comment by usmangani1** [comment]
> Thanks for making that change @usmangani1 - happy to merge once the build passes

@bblommers  Tests are passing in server mode and in normal mode One test is failing. Any idea what could be the reason here ? Can you please help me out ?

**Comment by bblommers** [comment]
Fixed @usmangani1 - the body can be None as well, not just empty

**Review by bblommers — APPROVED** [review]

**Comment by usmangani1** [comment]
> Fixed @usmangani1 - the body can be None as well, not just empty

Ahh, Got it. I missed that. Thanks for adding it

**Pull request merged**
