### PR TITLE
LambdaVersion providing ARN on __repr__

### PR DESCRIPTION
**Pull request by alanjds**
Just a dirty patch

### CODE REVIEW

**Comment by wyvern8** [comment]
@alanjds any progress on this one?

**Comment by alanjds** [comment]
Well, it fixes the problem pointed on #1588, but I had not pursued a full test.

And to be completely transparent, we had settled to use real AWS Lambdas on our CI for now. Then I am out of priority to fix localstack for now.

**Comment by spulec** [comment]
Thanks!

**Comment by beau6183** [comment]
When will this dirty patch make it into a release? Seems like  localstack/localstack#649 is being held up by it, unless I'm missing something...

**Pull request merged**
