### PR TITLE
Fix:Cloudformation descibe stacks special chars

### PR DESCRIPTION
**Pull request by usmangani1**
Fix:Cloudformation descibe stacks special chars
https://github.com/localstack/localstack/issues/3300

### CODE REVIEW

**Comment by usmangani1** [comment]
@bblommers Which version of black are we using to test the lint? I am using version 20.8b1 to format before raising the PR and some lint errors are being shown in travis.

**Comment by bblommers** [comment]
Hey @usmangani1, we're using black==19.10b0. There are quite a few bugs with the latest version (20.8b1), which is why we're pinning an older version.

**Review by bblommers — APPROVED** [review]
LGTM - thanks!

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.16.dev172

**Pull request merged**
