### PR TITLE
add test for prefix encoding

### PR DESCRIPTION
**Pull request by thehesiod**

### CODE REVIEW

**Comment by bblommers** [comment]
Hi @thehesiod, what is the expected/wrong behaviour here? This test passes on my local, both on flask 2.0.2 and 2.1.1

**Comment by thehesiod** [comment]
Interesting, it was failing for me locally with requirements.txt. let me check when I get home and report back

**Comment by bblommers** [comment]
Hi @thehesiod, any update on this?

**Comment by yan12125** [comment]
I guess thehesiod wanted to demonstrate that something goes wrong when the prefix contains `+`. Here are errors from _patched_ tests:

```
________________________________________________________________________ test_s3_server_bucket_create ________________________________________________________________________

self = <sure.AssertionBuilder object at 0x7f5f7146fb50>
args = (b'<?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>foobaz</Name><Prefix>bar baz</Prefix><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated></ListBucketResult>',)
kw = {}

    @wraps(func)
    def wrapper(self, *args, **kw):
        try:
>           value = func(self, *args, **kw)

/usr/lib/python3.10/site-packages/sure/__init__.py:408:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <sure.AssertionBuilder object at 0x7f5f7146fb50>
first = b'<?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>foobaz</Name><Prefix>bar baz</Prefix><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated></ListBucketResult>'
rest = (), collection_should = <sure.old.AssertionHelper object at 0x7f5f6f622890>

    @assertionmethod
    def within(self, first, *rest):
        if isinstance(first, Iterable):
            collection_should = AssertionHelper(first)
            if self.negative:
                return collection_should.does_not_contain(self.obj)
            else:
>               return collection_should.contains(self.obj)

/usr/lib/python3.10/site-packages/sure/__init__.py:680:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <sure.old.AssertionHelper object at 0x7f5f6f622890>, what = b'Contents'

    def contains(self, what):
>       assert what in self._src, '%r should be in %r' % (what, self._src)
E       AssertionError: b'Contents' should be in b'<?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>foobaz</Name><Prefix>bar baz</Prefix><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated></ListBucketResult>'

/usr/lib/python3.10/site-packages/sure/old.py:434: AssertionError

During handling of the above exception, another exception occurred:

self = <sure.AssertionBuilder object at 0x7f5f6f623040>, args = (b'Contents',), kw = {}

    @wraps(func)
    def wrapper(self, *args, **kw):
        try:
>           value = func(self, *args, **kw)

/usr/lib/python3.10/site-packages/sure/__init__.py:408:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <sure.AssertionBuilder object at 0x7f5f6f623040>, what = b'Contents'

    @assertionmethod
    def contain(self, what):
        obj = self.obj
        if self.negative:
            return expect(what).to.not_be.within(obj)
        else:
>           return expect(what).to.be.within(obj)

/usr/lib/python3.10/site-packages/sure/__init__.py:948:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <sure.AssertionBuilder object at 0x7f5f7146fb50>
args = (b'<?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>foobaz</Name><Prefix>bar baz</Prefix><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated></ListBucketResult>',)
kw = {}

    @wraps(func)
    def wrapper(self, *args, **kw):
        try:
            value = func(self, *args, **kw)
        except AssertionError as e:
>           raise AssertionError(e)
E           AssertionError: b'Contents' should be in b'<?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>foobaz</Name><Prefix>bar baz</Prefix><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated></ListBucketResult>'

/usr/lib/python3.10/site-packages/sure/__init__.py:410: AssertionError

During handling of the above exception, another exception occurred:

    def test_s3_server_bucket_create():
        test_client = authenticated_client()

        res = test_client.put("/", "http://foobaz.localhost:5000/")
        res.status_code.should.equal(200)

        res = test_client.get("/")
        res.data.should.contain(b"<Name>foobaz</Name>")

        res = test_client.get("/", "http://foobaz.localhost:5000/")
        res.status_code.should.equal(200)
        res.data.should.contain(b"ListBucketResult")

        for key_name in ('bar_baz', 'bar+baz'):
            res = test_client.put(f"/{key_name}", "http://foobaz.localhost:5000/", data="test value")
            res.status_code.should.equal(200)
            assert "ETag" in dict(res.headers)

            res = test_client.get("/", "http://foobaz.localhost:5000/", query_string={'prefix': key_name})
            res.status_code.should.equal(200)
>           res.data.should.contain(b"Contents")

tests/test_s3/test_server.py:55:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <sure.AssertionBuilder object at 0x7f5f6f623040>, args = (b'Contents',), kw = {}

    @wraps(func)
    def wrapper(self, *args, **kw):
        try:
            value = func(self, *args, **kw)
        except AssertionError as e:
>           raise AssertionError(e)
E           AssertionError: b'Contents' should be in b'<?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>foobaz</Name><Prefix>bar baz</Prefix><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated></ListBucketResult>'

/usr/lib/python3.10/site-packages/sure/__init__.py:410: AssertionError
```

**Comment by bblommers** [comment]
Looks like this is failing due to an upgrade of `werkzeug` - the test fails with werkzeug >= 2.1.0, but passes against 2.0.x. (Locally I had an outdated version, which is why I couldn't reproduce it.)
Will continue to look into the root cause.

**Comment by bblommers** [comment]
Thanks again for raising this @thehesiod and @yan12125 - this should now be fixed as of moto >= 3.1.8.dev13. I'll close this, but do let me know if there are any other issues!

**Pull request closed without merging**
