### PR TITLE
Enchancement -  Adding get-metric-data functionality in aws cloudwatch

### PR DESCRIPTION
**Pull request by usmangani1**
https://github.com/localstack/localstack/issues/2300

Implemented functionality for cloudwatch get-metric-data.

### CODE REVIEW

**Comment by usmangani1** [comment]
> [localstack/localstack#2300](https://github.com/localstack/localstack/issues/2300)
> 
> Implemented functionality for cloudwatch get-metric-data.

@bblommers Added a new cloudwatch functionality,Need your help in linting and getting it merged.Please

**Comment by bblommers** [comment]
Hi @usmangani1, there's an outstanding PR for this: #2848 

Will close this in favour of mine, since this PR lacks support for various 'Stat' options (Sum, Average, Min Max)
The rest of the functionality looks the same, but feel free to contribute to my PR if I've missed anything!

**Comment by usmangani1** [comment]
> Hi @usmangani1, there's an outstanding PR for this: #2848
> 
> Will close this in favour of mine, since this PR lacks support for various 'Stat' options (Sum, Average, Min Max)
> The rest of the functionality looks the same, but feel free to contribute to my PR if I've missed anything!

@bblommers  Awesome.I just had a look at the PR it looks great.Is there any place from where we can get to know if some implementation is being done ? so that people who are planning to take this will get to know someone else is working in this and skip , concentrate on something else ?

**Comment by bblommers** [comment]
@usmangani1 Thanks for the review.
There isn't really a centralized index on what's being worked on - I typically just search for the method I'm about to implement in the PR's and issues

**Pull request closed without merging**
