### PR TITLE
Add registeredAt to ecs container instance

### LINKED ISSUE #3352: `mock_ecs.describe_container_instances` missing value `registeredAt`
The [official ECS documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html#ECS.Client.describe_container_instances) states that the response of `client.describe_container_instances()` contains :
>registeredAt (datetime) --
The Unix timestamp for when the container instance was registered.

But as far as I know, moto mock of that call doesn't.

### to Reproduce:
Inspired from [`test_run_task()`](https://github.com/spulec/moto/blob/a668349a70ffce571c74c77074e6270f3cb59dd7/tests/test_ecs/test_ecs_boto3.py#L1087)

```python 
@mock_ec2
@mock_ecs
def test():
    client = boto3.client("ecs", region_name="us-east-1")
    ec2 = boto3.resource("ec2", region_name="us-east-1")

    test_cluster_name = "test_ecs_cluster"

    _ = client.create_cluster(clusterName=test_cluster_name)

    test_instance = ec2.create_instances(
        ImageId="ami-1234abcd", MinCount=1, MaxCount=1
    )[0]

    instance_id_document = json.dumps(
        ec2_utils.generate_instance_identity_document(test_instance)
    )

    response = client.register_container_instance(
        cluster=test_cluster_name, instanceIdentityDocument=instance_id_document
    )

    _ = client.register_task_definition(
        family="test_ecs_task",
        containerDefinitions=[
            {
                "name": "hello_world",
                "image": "docker/hello-world:latest",
                "cpu": 1024,
                "memory": 400,
                "essential": True,
                "environment": [
                    {"name": "AWS_ACCESS_KEY_ID", "value": "SOME_ACCESS_KEY"}
                ],
                "logConfiguration": {"logDriver": "json-file"},
            }
        ],
    )
    response = client.run_task(
        cluster="test_ecs_cluster",
        overrides={},
        taskDefinition="test_ecs_task",
        count=2,
        startedBy="moto",
    )
    node = self.ecs.describe_container_instances(
        cluster="test_ecs_cluster",
        containerInstances=self.ecs.list_container_instances(cluster="test_ecs_cluster", status="ACTIVE")["containerInstanceArns"],
    )
    print(node["containerInstances"][0]["registeredAt"]) #KeyError: 'registeredAt'
```
Logs : 
```
Traceback (most recent call last):
  File "/path/to/python3.6/site-packages/moto/core/models.py", line 100, in wrapper
    result = func(*args, **kwargs)
  File "/path/to/python3.6/site-packages/moto/core/models.py", line 100, in wrapper
    result = func(*args, **kwargs)
  File "/path/topython3.6/site-packages/moto/core/models.py", line 100, in wrapper
    result = func(*args, **kwargs)
  File "/path/to/my/file.py", line 147, in test_test
    print(node["containerInstances"][0]["registeredAt"])
KeyError: 'registeredAt'
```

moto version : 1.3.16

This attribute is quite important to us, because we want to have a script that shuts down instances if they are "too old" or something like that, and properly testing that script is key.

### PR DESCRIPTION
**Pull request by gruebel**
Fixes #3352 

Easy fix and adjusted test.

### CODE REVIEW

**Comment by gruebel** [comment]
@bblommers are you interested in participating Hacktoberfest with this repo again?

**Comment by gruebel** [comment]
@bblommers and could you also restart the Travis build for Python 3.6, it failed during a `batch` test

**Comment by bblommers** [comment]
> @bblommers are you interested in participating Hacktoberfest with this repo again?

I'll leave that up to @spulec

**Review by bblommers — APPROVED** [review]
Thanks for the PR!

**Comment by spulec** [comment]
Yeah, I'm down. Let me know if we need to do anything to mark the repo as such.

**Comment by gruebel** [comment]
@spulec that would be awesome! As far as I understood you just have to add **hacktoberfest** to your repo topics.
https://hacktoberfest.digitalocean.com/hacktoberfest-update
and then you and @bblommers can also add hacktoberfest atgs to several issues to make it easy for new comers to find this repo 😄

**Comment by spulec** [comment]
Added the tag and labeled this PR as such. Let me know if I need to do anything else!

**Comment by gruebel** [comment]
@spulec I think you just need to add it to the topics of the repo, no need to add to every PR 😄 
image

**Pull request merged**
