### PR TITLE
s3 key_name encoding should be variable

### PR DESCRIPTION
**Pull request by pinzon**
This PR corrects the last problem commented in #5181 by @tsiq-rob.

### CODE REVIEW

**Review by bblommers — APPROVED** [review]

**Comment by bblommers** [comment]
Does this release fix the problem for you, @tslq-rob?

**Comment by tsiq-rob** [comment]
> Does this release fix the problem for you, @tslq-rob?

Thanks for the fix. I will investigate soon and let you know whether it resolves the issue we saw.

**Comment by tsiq-rob** [comment]
Yes, the issue seems to be resolved. Thanks again!

**Comment by bblommers** [comment]
Thanks for confirming @tsiq-rob, and thanks again for the fixing it @pinzon!

**Pull request merged**
