### PR TITLE
Implemented describe_instance_credit_specifications function in ec2 #…

### PR DESCRIPTION
**Pull request by usmangani1**
Implemented describe_instance_credit_specifications function in ec2 #2150 localstack

### CODE REVIEW

**Comment by usmangani1** [comment]
> Hi @usmangani1, welcome to Moto! Thanks for your PR
> 
> Looks like Travis isn't happy about the linting -can you run black on the moto and tests directory?
> Once the build passes I'd be happy to merge
> 
> https://travis-ci.org/github/spulec/moto/jobs/671711769?utm_medium=notification&utm_source=github_status

Could you help me a bit by pointing where exactly its throwing linter errors? That would fasten the process.

**Comment by bblommers** [comment]
You run the following command to lint automatically:
```black moto tests```

After that you can run ```make lint``` to verify

Make sure this is done in a Python3.7 env, as that's the only env that currently supports black

**Comment by usmangani1** [comment]
> You run the following command to lint automatically:
> `black moto tests`
> 
> After that you can run `make lint` to verify
> 
> Make sure this is done in a Python3.7 env, as that's the only env that currently supports black

Any suggestion how to do it on python 2.7?

**Comment by bblommers** [comment]
Don't think that's supported, unfortunately.

If you don't have access to 3.7 I'm happy to do it for you? I can just push the changes to your branch

**Comment by usmangani1** [comment]
> Don't think that's supported, unfortunately.
> 
> If you don't have access to 3.7 I'm happy to do it for you? I can just push the changes to your branch

Yes please.

**Comment by usmangani1** [comment]
> Don't think that's supported, unfortunately.
> 
> If you don't have access to 3.7 I'm happy to do it for you? I can just push the changes to your branch
@bblommers  will you be able to fix it now ?

**Comment by bblommers** [comment]
I'm mobile now, but will do it tomorrow @usmangani1

**Pull request merged**
