### PR TITLE
IAM Improvements

### PR DESCRIPTION
**Pull request by mikegrima**
Made a bunch of fixes and additions:

Fixes:
- Fixed InstanceProfiles having `Path` set to `None`.
- Added in some dynamic `CreateDate`s.
- Fixed issue where the `InstanceProfileId` wasn't being received.

Additions:
- Added support for IAM User Self-Signing Certificates

Rebased with the latest and greatest updates and changes.

### CODE REVIEW

**Comment by mikegrima** [comment]
Works on my tests internally.

**Comment by mikegrima** [comment]
@spulec The newest features added are working internally for me. Can you please merge?

**Comment by mikegrima** [comment]
@JackDanger @spulec bump.

**Comment by spulec** [comment]
Thanks Mike!

**Pull request merged**
