### PR TITLE
Implement groups for cognito-idp

### PR DESCRIPTION
**Pull request by garyd203**

### CODE REVIEW

**Comment by garyd203** [comment]
I notice that the travis run failed because of a timing-related error in an unrelated test. Do I need to do anything about this?

The test that failed was this (running in `TEST_SERVER_MODE` in Python 2.7):

```
======================================================================
FAIL: Failure: AssertionError (given
X = datetime.datetime(2018, 7, 23, 11, 17, 44, tzinfo=tzlocal())
    and
Y = datetime.datetime(2018, 7, 23, 11, 17, 45, tzinfo=tzlocal())
X != Y)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/spulec/moto/tests/test_ec2/test_elastic_block_store.py", line 593, in <module>
    @mock_ec2
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/freezegun/api.py", line 615, in freeze_time
    return freeze_time(time_to_freeze(), tz_offset, ignore, tick)
  File "/home/travis/build/spulec/moto/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "/home/travis/build/spulec/moto/tests/test_ec2/test_elastic_block_store.py", line 623, in test_copy_snapshot
    getattr(source, attrib).should.equal(getattr(dest, attrib))
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/sure/__init__.py", line 384, in wrapper
    value = func(self, *args, **kw)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/sure/__init__.py", line 660, in equal
    raise error
AssertionError: given
X = datetime.datetime(2018, 7, 23, 11, 17, 44, tzinfo=tzlocal())
    and
Y = datetime.datetime(2018, 7, 23, 11, 17, 45, tzinfo=tzlocal())
X != Y
>>  raise AssertionError(u'given\nX = datetime.datetime(2018, 7, 23, 11, 17, 44, tzinfo=tzlocal())\n    and\nY = datetime.datetime(2018, 7, 23, 11, 17, 45, tzinfo=tzlocal())\nX != Y',)
    
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost:5000
urllib3.connectionpool: DEBUG: http://localhost:5000 "POST /moto-api/reset HTTP/1.1" 200 16
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): localhost:5000
urllib3.connectionpool: DEBUG: http://localhost:5000 "POST /moto-api/reset HTTP/1.1" 200 16
--------------------- >> end captured logging << ---------------------
```

The test looks to rely on frozen time in order to ensure correct results. Does this make sense when the subject under test is running in a separate docker container? Would it be appropriate to skip these `@freeze_time` tests when running `TEST_SERVER_MODE`

**Comment by terrycain** [comment]
You generally skip the frozentime checks when its running in server mode, check some of the other modules as i know a few do that.

**Comment by terrycain** [comment]
Looks good, just fix the failing test

**Comment by garyd203** [comment]
Thanks @terrycain , the failing test appears to be unrelated to this changeset. I have put together PR #1737 to skip all the `freeze_time` tests when testing server mode. When that PR is merged, I will rebase this PR and it should all be good.

**Comment by terrycain** [comment]
@garyd203 :+1:

**Comment by spulec** [comment]
Thanks!

**Pull request merged**
