### PR TITLE
add pass_through option to responses

### LINKED ISSUE #948: can't use responses
with v1, since moto vendors in `responses`, it's impossible to use `responses` for mocking non-aws calls. example:

```py
with _responses.RequestsMock() as rsps:
    rsps.add(rsps.GET, 'http://foo')
    with moto.mock_sns():
       requests.get('http://foo')
```

this used to work on < v1, on v1 it raises a connection refused error because basically requests is patched twice by two different modules

### PR DESCRIPTION
**Pull request by itajaja**
fixes #948

### CODE REVIEW

**Comment by itajaja** [comment]
ping :)

**Comment by JackDanger** [comment]
@itajaja I *think* I understand the reason for this change but could you explain it to us just the same? I'm not sure quite when I'd use this but I suspect it's really useful.

**Comment by itajaja** [comment]
look at the first message on #948, this will enable using responses for additional mocking outside moto

**Comment by JackDanger** [comment]
Ah, this looks pretty good then. Passing to @spulec for approval but this looks good to me because it allows developers to work around the hard-wired dependency.

**Comment by itajaja** [comment]
I actually opened a PR upstram to allow that, but didn't receive a response yet: getsentry/responses#150

**Comment by spulec** [comment]
Looks great! Thanks everyone.

**Comment by itajaja** [comment]
Thanks! After a new release is cut, we can finally update to Moto 1 :)

**Pull request merged**
