### PR TITLE
Bugfix for put_scaling_policy in applicationautoscaling.

### PR DESCRIPTION
**Pull request by rkstrickland**
https://github.com/spulec/moto/issues/4053

### CODE REVIEW

**Comment by rkstrickland** [comment]
Not sure what the lint error is about. When I run black locally, it shows that all is well.

**Comment by bblommers** [comment]
Hi @rkstrickland, thanks for providing a fix! Make sure that you're using the right version of black (black==19.10b0), as different versions will produce different formatting

**Comment by rkstrickland** [comment]
Thanks @bblommers. I re-formatted using the specified version and looks like tests just need to run again.

**Review by bblommers — APPROVED** [review]
LGTM!

**Pull request merged**
