### PR TITLE
moto/issues/2670 | Moved population of user attributes from accessToken to idToken

### PR DESCRIPTION
**Pull request by franz-see**

### CODE REVIEW

**Comment by gruebel** [comment]
Also here, please run the command `black --check moto/ tests/` locally to format your files and then the build will become green.

**Comment by franz-see** [comment]
Thanks @gruebel . i've now pushed another commit fixing the formatting. This is now the output of `black --check moto/ tests/`

```
$ black --check moto tests
All done! ✨ 🍰 ✨
583 files would be left unchanged.
```

**Comment by bblommers** [comment]
Hi @franz-see - thanks for your contributions! It looks like your other PR introduced some conflicts - happy to merge after those are fixed.

**Comment by franz-see** [comment]
@bblommers fixed merge issues

**Comment by bblommers** [comment]
Thanks @franz-see!

**Pull request merged**
