### PR TITLE
Be able to change user attributes in cognito-idp.

### PR DESCRIPTION
**Pull request by garyd203**
Update existing partial implementation to store attributes as a Python dict, and only convert to a list-of-name-value-pairs when required

### CODE REVIEW

**Comment by coyotecote** [comment]
Will this PR get merged to master anytime soon? I need the "admin_update_user_attributes" API. Thanks

**Comment by garyd203** [comment]
I have rebased this PR to be against current git master branch, in case that helps it be accepted

**Comment by mikegrima** [comment]
@coyotecote Have you tested if this PR works for you locally?

**Comment by bblommers** [comment]
The `admin_update_user_attributes` was merged with #2185, and `admin_delete_user_attributes` was merged with #4487, so the features of this PR are all implemented now as far as I can tell.

Will close this, but let me know if I've missed anything.

**Comment by garyd203** [comment]
Thanks @bblommers :-)

**Pull request closed without merging**
