### PR TITLE
Import time reduction

### PR DESCRIPTION
**Pull request by Procrat**
This speeds up import time from ~5.4s to 0.2s on my machine.

### CODE REVIEW

**Comment by Procrat** [comment]
Rebased. I can't reproduce the failing tests on my machine.

**Comment by bblommers** [comment]
Hi @Procrat - the failing test was due to a bug in boto (https://github.com/spulec/moto/issues/2774), but this has now been fixed in master.
Could you rebase and try again?

**Comment by Procrat** [comment]
Thank you for letting me know, @bblommers! And thank you for the review!

**Comment by Procrat** [comment]
@spulec Just to ensure we're on the same page, is there's anything you expect from my side?

(I'm just wondering; I definitely don't want to put pressure on you, because I understand that managing a FOSS project on the side is tough!)

**Comment by DenverJ** [comment]
I've been using for the last week or so and it has been such a time saver!!

**Comment by spulec** [comment]
@Procrat thanks for your patience! This looks great!

If you can rebase one more time, we will be happy to merge.

(if another maintainer sees the rebase changes before I do, feel free to merge)

**Comment by Procrat** [comment]
Thanks, @spulec! I've rebased now.

**Comment by asherf** [comment]
@bblommers I am pretty sure this PR introduced a regression.
I did this:
```
(venv) ➜  moto git:(travis) python
Python 3.7.4 (default, Oct  9 2019, 12:56:08)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from moto.iam import iam_backend
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/asher/projects/moto/moto/iam/__init__.py", line 2, in <module>
    from .models import iam_backend
  File "/Users/asher/projects/moto/moto/iam/models.py", line 17, in <module>
    from moto.core.exceptions import RESTError
  File "/Users/asher/projects/moto/moto/core/__init__.py", line 4, in <module>
    from .responses import ActionAuthenticatorMixin
  File "/Users/asher/projects/moto/moto/core/responses.py", line 14, in <module>
    from moto.core.access_control import IAMRequest, S3IAMRequest
  File "/Users/asher/projects/moto/moto/core/access_control.py", line 28, in <module>
    from moto.iam.models import Policy
ImportError: cannot import name 'Policy' from 'moto.iam.models' (/Users/asher/projects/moto/moto/iam/models.py)
>>>
(venv) ➜  moto git:(travis) git checkout f33e810e15acee2a03e872f104f117c1cbdbd0dc
Note: switching to 'f33e810e15acee2a03e872f104f117c1cbdbd0dc'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at f33e810e Merge pull request #2921 from getglad/support_optin_regions
(venv) ➜  moto git:(f33e810e) python
Python 3.7.4 (default, Oct  9 2019, 12:56:08)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from moto.iam import iam_backend
>>>

```

Screenshot 2020-04-29 08 51 00

**Comment by Procrat** [comment]
It's interesting to me that these circular dependencies didn't come up before. Perhaps the import system is doing something clever there to automatically fix certain cases of circular dependencies?

I've attached a patch here to fix this in the short term. (Happy to create a PR if wanted.)

However, in my experience, a circular dependency tends to be a red flag of some underlying structural issue. I would urge someone who's more familiar with the codebase to have a closer look at [this commit](https://github.com/spulec/moto/pull/2697/commits/9c13798f785b1a920eb7c703f659c94c45417b6f) and this patch and see if the dependency cycle is intended. For example, I would expect that the mocks for specific AWS services depend on `moto.core` but never the other way around. `moto.core.access_control` depends `moto.iam` and `moto.sts` which caused this issue.

```patch
diff --git i/moto/core/responses.py w/moto/core/responses.py
index 9a46f8ac..527dcc7d 100644
--- i/moto/core/responses.py
+++ w/moto/core/responses.py
@@ -11,7 +11,6 @@ import requests

 import pytz

-from moto.core.access_control import IAMRequest, S3IAMRequest
 from moto.core.exceptions import DryRunClientError

 from jinja2 import Environment, DictLoader, TemplateNotFound
@@ -134,9 +133,11 @@ class ActionAuthenticatorMixin(object):
             ActionAuthenticatorMixin.request_count += 1

     def _authenticate_and_authorize_normal_action(self):
+        from moto.core.access_control import IAMRequest
         self._authenticate_and_authorize_action(IAMRequest)

     def _authenticate_and_authorize_s3_action(self):
+        from moto.core.access_control import S3IAMRequest
         self._authenticate_and_authorize_action(S3IAMRequest)

     @staticmethod
```

**Pull request merged**
