### PR TITLE
Add cloudwatch tags

### PR DESCRIPTION
**Pull request by gruebel**
Had to also add the possibility to search for AMIs by `amazon` owner alias, because of a Terraform test, which queries that data.

I also added several missing parameters, I think that's all at the moment and Terraform is also happy 😄 

image

### CODE REVIEW

**Comment by bblommers** [comment]
Hi @gruebel, looks like the EC2 AMI filter was already added this morning, in this PR: https://github.com/spulec/moto/pull/4175/files

**Comment by gruebel** [comment]
yeah, I also saw that now 😄 looks much better than my simple fix 💪 rebasing right now and have to add an AMI to the json file, which is used by one of the Terraform tests.

**Comment by gruebel** [comment]
Forgot to mention, this also fixes #4020

**Review by bblommers — APPROVED** [review]
Awesome - thanks @gruebel!

**Pull request merged**
