### PR TITLE
Add support for using arns in lambda requests

### PR DESCRIPTION
**Pull request by ianyon**
Lambda requests can use the function name or function arn, so I modified the parsing to parse for arn expressions now that there are functions in moto to search for name or arn

### CODE REVIEW

**Comment by bblommers** [comment]
Hi @ianyon - thanks for your PR, looks good to me.
Can you just add a few tests, to verify that it works?

**Comment by mikegrima** [comment]
I believe I may have beat you to this: https://github.com/spulec/moto/pull/2725/files

Does the PR above address your issue?

**Comment by ianyon** [comment]
Hi @mikegrima In part, but I also needed this in the lambda put_configuration. I haven't found time to add the tests yet, but I'll update the Pull Request as soon as I can.

**Comment by bblommers** [comment]
Closing, as this has now been implemented by #3681

**Pull request closed without merging**
