### PR TITLE
Extending IoT Policy and Jobs functionality

### PR DESCRIPTION
**Pull request by sthuber90**

### CODE REVIEW

**Comment by terrycain** [comment]
Can you resolve conflicts

**Comment by sthuber90** [comment]
@terrycain I've resolved the conflicts

**Comment by terrycain** [comment]
Can you see why the server mode tests are failing?

**Comment by sthuber90** [comment]
It fails with message:
```
Traceback (most recent call last):
  File "/opt/python/3.7.1/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/opt/python/3.7.1/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/python/3.7.1/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/python/3.7.1/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/python/3.7.1/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/opt/python/3.7.1/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/opt/python/3.7.1/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/opt/python/3.7.1/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/opt/python/3.7.1/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "wait_for.py", line 24, in <module>
    urllib.urlopen('http://localhost:5000/', timeout=1)
  File "/opt/python/3.7.1/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/python/3.7.1/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/opt/python/3.7.1/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/opt/python/3.7.1/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/opt/python/3.7.1/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/opt/python/3.7.1/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
The command "python setup.py sdist
```

**Comment by terrycain** [comment]
Yeah so the server is not starting for some reason

**Comment by sthuber90** [comment]
@terrycain I fixed the build. It was a line-ending issue in the repo. Is it all good to get merged now?

**Comment by sthuber90** [comment]
What can I do, so this PR is getting merged?

**Comment by spulec** [comment]
Can you undo the unrelated whitespace changes to the cloudformation files? Once that is done, I'll be happy to review!

**Comment by sthuber90** [comment]
I changed the cloudformation files to what they were before

**Comment by bblommers** [comment]
More conflicts I'm afraid @sthuber90, but other than that - LGTM.
I'll leave it to @spulec  or @terrycain to have a second review due to the size

**Comment by sthuber90** [comment]
@spulec & @terrycain anything else needed from my side?

**Comment by spulec** [comment]
Looks great; thanks for all of the work!

**Pull request merged**
