### PR TITLE
Add outputs and vpc interfaces to a mediaconnect flow

### PR DESCRIPTION
**Pull request by blancheta**
The aim of this PR is to add support for:
- add_flow_outputs
- add_flow_vpc_interfaces

### CODE REVIEW

**Review by bblommers — CHANGES_REQUESTED** [review]
Hi @blancheta, thanks for the PR!
Can you add a few negative tests as well, to verify that the two NotFoundExceptions are raised when passing in an unknown `flowArn`? 

See here for an example:
https://github.com/spulec/moto/blob/c2aa707878346382d941b27c4370923f04ac7610/tests/test_mediapackage/test_mediapackage.py#L88

**Comment by bblommers** [comment]
Looks like the linter fails as well - please install `black==19.10b0` and run `make format` to fix the formatting

**Comment by bblommers** [comment]
Hope you don't mind @blancheta - I added the appropriate URLs to make the ServerMode tests pass

**Review by bblommers — APPROVED** [review]
LGTM!

**Comment by blancheta** [comment]
> LGTM!

Cheers!

**Pull request merged**
