### PR TITLE
Fix #3996

### LINKED ISSUE #3996: delete_message_batch doesn't handle duplication correctly (incorrect exception raised)
Moto version: 2.0.8
boto3 version: 1.17.88
botocore version: 1.20.88

```python
@mock_sqs
def test_duplicate_bug() -> None:
    client = boto3.client("sqs")
    queue_url = client.create_queue(QueueName="test_inbound_queue")["QueueUrl"]
    client.send_message(QueueUrl=queue_url, MessageBody="coucou")

    messages = client.receive_message(QueueUrl=queue_url, WaitTimeSeconds=0)["Messages"]
    assert messages, "at least one msg"
    entries = [
        {"Id": msg["MessageId"], "ReceiptHandle": msg["ReceiptHandle"]}
        for msg in [messages[0], messages[0]]
    ]

    # with moto, this raises botocore.errorfactory.ReceiptHandleIsInvalid
    # however, running this code against a real AWS queue would raise
    # botocore.errorfactory.BatchEntryIdsNotDistinct
    client.delete_message_batch(QueueUrl=queue_url, Entries=entries)
```

### PR DESCRIPTION
**Pull request by geekingfrog**
This should fix https://github.com/spulec/moto/issues/3996

### CODE REVIEW

**Review by bblommers — CHANGES_REQUESTED** [review]
Hey @geekingfrog, thanks for the PR! The logic doesn't seem quite right, as it will delete the first messate, and only throw the error against the second message. 
Just checked this against AWS - they don't delete the message at all when this error scenario occurs.

Would be good to have an assert for this behaviour as well, i.e.:

```
messages = client.receive_message(QueueUrl=queue_url, WaitTimeSeconds=0)["Messages"]
assert messages, "at least one msg"
...
# batch_delete
...
messages = client.receive_message(QueueUrl=queue_url, WaitTimeSeconds=0)["Messages"]
assert messages, "at least one msg"
```

**Comment by geekingfrog** [comment]
You're right, it's a good catch. I'll amend that soon(ish)

**Comment by geekingfrog** [comment]
Alright, I fixed it and added a test to make sure it stays fixed.

**Review by bblommers — APPROVED** [review]
LGTM!

**Pull request merged**
