### PR TITLE
Fix autoscaling tags

### LINKED ISSUE #3009: CloudFormation autoscaling group PropagateAtLaunch not setting properly
When creating a CloudFormation autoscaling group, PropagateAtLaunch for tags is being reported as 'False' even though it was set to 'True' in the template

### PR DESCRIPTION
**Pull request by zbrookle**
Fixes #3009

### CODE REVIEW

**Comment by zbrookle** [comment]
Fixes #3009

**Comment by zbrookle** [comment]
@spulec Is there any way that you could re run the pipeline? It only failed on python 2.7 and I'm fairly certain that the test that failed is related to a network issue rather than a change I made

**Comment by aidan-** [comment]
@zbrookle Build failure is probably related to #3008 .  My PR build (#3007) is failing with the same issue.

**Comment by bblommers** [comment]
That's correct, @aidan-. Hopefully we can get the build fixed in #3008 soon - after that I'll merge both your PRs

**Comment by zbrookle** [comment]
@bblommers Ok great sounds good!

**Pull request merged**
