### PR TITLE
Add tag get_resources support for target groups

### LINKED ISSUE #3011: Add tag get_resources support for target groups
Hi there,

I would like to leverage the resource tagging endpoint to search for target groups. I have also noticed a small typo in the handling of tags for elbv2 in the code (is currently `elasticloadbalancer`, should be `elasticloadbalancing` as per [user guide](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_elasticloadbalancingv2.html). I have linked a pull request.

Regards,
Ben

### PR DESCRIPTION
**Pull request by ben-nz**
Also fixed resource identifier for elb (was `elasticloadbalancer`, changed to `elasticloadbalancing` as per [user guide](https://docs.aws.amazon.com/IAM/latest/UserGuide/list_elasticloadbalancingv2.html). Resolves #3011

### CODE REVIEW

**Comment by ben-nz** [comment]
Would appreciate some help in evaluating why the tests failed, thanks

**Comment by yan12125** [comment]
Seems you got the same issue as me - new cfn-lint breaks tests. I have a fix at https://github.com/spulec/moto/pull/3015.

Another issue is that Python 2 tests are currently broken - https://github.com/spulec/moto/issues/3008.

**Comment by ben-nz** [comment]
Thanks @yan12125, do you recommend I make the fix in my PR as well or wait until your PR hits master and then rebase?

**Comment by ben-nz** [comment]
test_get_resources_ec2 was failing since it was checking for number of resources created in a shared fixture. For now I have moved test_get_resources_s3 to the bottom so that test_get_resources_ec2 is first test. Also added tag filter testing for target groups.

**Comment by yan12125** [comment]
> do you recommend I make the fix in my PR as well or wait until your PR hits master and then rebase?

I wasn't sure about it. Now that test failures are fixed with #3024, so rebasing should work :)

**Comment by bblommers** [comment]
No need to rebase @ben-nz - I already restarted the build. Travis checks-out master and simply applies the new commits, so the tests are already fixed when rerunning it.

**Pull request merged**
