### PR TITLE
Fix ApiGateway key identification

### PR DESCRIPTION
**Pull request by haidaraM**
Hello :), here is my firt PR that fixes an issue with API Gateway keys identification

API Gateway keys are identified by their ids and not their values

- https://docs.aws.amazon.com/cli/latest/reference/apigateway/get-api-key.html#examples
- http://boto3.readthedocs.io/en/latest/reference/services/apigateway.html#APIGateway.Client.get_api_key

### CODE REVIEW

**Comment by kingbuzzman** [comment]
Oops. Missed that completely. Makes sense to me.

**Comment by haidaraM** [comment]
Someone to check this PR ?

**Comment by kingbuzzman** [comment]
They're a little slow, give them time. Remember no one gets paid for this ;) My pr sat around for like 2 weeks.. so, you're still doing better.

**Comment by haidaraM** [comment]
Yeah absolutely agree with you :) Not so critical...

**Comment by spulec** [comment]
Sorry it took a bit to review.

Thanks for the contribution and welcome to Moto!

**Comment by haidaraM** [comment]
No worries :) and thank you for your great library

**Pull request merged**
