### PR TITLE
Added references to moto.iam.models.ACCOUNT_ID instead of hardcoded id

### PR DESCRIPTION
**Pull request by fabioasdias**
This adds support to mocking the AccountID by replacing all hardcoded '123456789012' that referenced account ids with imports from moto.iam.models.

Related issue #2545

### CODE REVIEW

**Comment by fabioasdias** [comment]
I'll fix the linting issue soonish, but I'll hold until master is building to try a new commit....

**Comment by fabioasdias** [comment]
It's easy enough to do, especially since all imports I used are exactly the same. And I was thinking about allowing this to be an environment variable, like MOTO_ACCOUNT_ID. Thoughts?

**Comment by mikegrima** [comment]
Env var support should be fine. But not in `moto.iam`.

**Comment by fabioasdias** [comment]
Done (ish), I'll add a test for this on my backlog (with a new PR)

**Pull request merged**
