### PR TITLE
Support x-amz-tagging-directive in s3 copy_object

### LINKED ISSUE #2131: s3.copy_object doesn't honor tagging directive
When I copy an S3 object in moto the tagset is always copied with it, even when I request a replacement tagset.

For example:

```python
import moto
import boto3

BUCKET = 'testbucket'

with moto.mock_s3():
    c = boto3.client('s3')
    c.create_bucket(Bucket=BUCKET)
    c.put_object(Bucket=BUCKET, Key='src', Body=b'', Tagging='tags=old')
    c.copy_object(
        CopySource={'Bucket': BUCKET, 'Key': 'src'},
        Bucket=BUCKET,
        Key='dst',
        TaggingDirective='REPLACE',
        Tagging='tags=new',
    )
    r = c.get_object_tagging(Bucket=BUCKET, Key='dst')
    print('tags for new object (moto s3):', r['TagSet'])
```

Prints:

```
tags for new object (moto s3): [{'Key': 'tags', 'Value': 'old'}]
```

But when running this in actual S3:

```python
import boto3

BUCKET = '...'

c = boto3.client('s3')
c.put_object(Bucket=BUCKET, Key='src', Body=b'', Tagging='tags=old')
c.copy_object(
    CopySource={'Bucket': BUCKET, 'Key': 'src'},
    Bucket=BUCKET,
    Key='dst',
    TaggingDirective='REPLACE',
    Tagging='tags=new',
)
r = c.get_object_tagging(Bucket=BUCKET, Key='dst')
print('tags for new object (real s3):', r['TagSet'])
```

I get the expected output:

```
tags for new object (real s3): [{'Key': 'tags', 'Value': 'new'}]
```

Versions used:

moto==1.3.7
boto3==1.7.47
botocore==1.12.123

### PR DESCRIPTION
**Pull request by niklasj**
Fixes #2131

### CODE REVIEW

**Comment by terrycain** [comment]
Fix merge conflicts and tests and ill merge

**Comment by chenlu-wang** [comment]
Is this PR still on track to merge?

**Comment by spulec** [comment]
If someone can get it working and the tests to pass, we'll be happy to merge.

**Comment by niklasj** [comment]
I've fixed the merge conflict and lint errors. Unfortunately I'm not able to successfully run the test suite successfully on my local environment on either master or this branch. At least the number of errors match, so hopefully it's just my environment…

**Comment by spulec** [comment]
Thanks and welcome to Moto!

**Pull request merged**
