### PR TITLE
validate target group name

### PR DESCRIPTION
**Pull request by kawasakitoshiya**
API doc

http://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateTargetGroup.html

```
Name
The name of the target group.

This name must be unique per region per account, can have a maximum of 32 characters, must contain only alphanumeric characters or hyphens, and must not begin or end with a hyphen.
```

### CODE REVIEW

**Comment by JackDanger** [comment]
@kawasakitoshiya Just leave a comment whenever you'd like this merged - this looks great!

**Comment by kawasakitoshiya** [comment]
I added undocumented validation :) pls merge if it's okay.

**Comment by kawasakitoshiya** [comment]
And, am gonna make some small PRs, but it's not so hurry. please review just when you have time :)

**Comment by JackDanger** [comment]
@kawasakitoshiya thanks so much!

**Pull request merged**
