### PR TITLE
Adding iam credentials report

### PR DESCRIPTION
**Pull request by mfulleratlassian**
Added IAM credentials report

### CODE REVIEW

**Comment by spulec** [comment]
It looks like there is one python3 str/bytes issue. If we can get that fixed, I'm happy to merge.

**Comment by mfulleratlassian** [comment]
ill have to configure myself a python 3.3 environment to be able to run the unit tests just trying to iron out the crinkles in the tests. Pretty busy at work atm might get some more time late in the week.

Mike

**Comment by spulec** [comment]
No rush. If I get a minute, I'll try to dig into it.

**Comment by mfulleratlassian** [comment]
Green builds - Yay

**Comment by spulec** [comment]
Thank you!

**Pull request merged**
