### PR TITLE
fixed route-table vpc-endpoint integration

### PR DESCRIPTION
**Pull request by macnev2013**
# Fixed
- VPC Endpoint integration with route table
- Prefix List as route table destination

# TF Test Passed
- TestAccAWSRouteTable_IPv4_To_InternetGateway
- TestAccAWSRouteTable_GatewayVpcEndpoint

### CODE REVIEW

**Comment by macnev2013** [comment]
Hi @bblommers , Can you please review this PR a in a bit detail and see if it will any side-effects on other functionalities? (then we can fix the tests accordingly) 

Thanks

**Comment by bblommers** [comment]
> 
> 
> Hi @bblommers , Can you please review this PR a in a bit detail and see if it will any side-effects on other functionalities? (then we can fix the tests accordingly)
> 
> Thanks

Hi @macnev2013, I'm not aware of anything that would be impacted by this 👍

**Comment by macnev2013** [comment]
Hi @bblommers,
Short Note: I just discovered while using `boto3.resource` to get the routes in route table using `route_table.routes` does not contain any route with IPv6 in the result.
Alternatively we can use `route_table.routes_attribute` to retrive all the routes.
Or we can use `boto3.client` for the same

**Review by bblommers — APPROVED** [review]
LGTM! Thanks @macnev2013

**Pull request merged**
