### PR TITLE
Clean up README, and distribute info over the external docs

### PR DESCRIPTION
**Pull request by bblommers**
The README became a bit unwieldy, so I've distributed that info across the docs-page. Hopefully this makes things more readable.

Noticable changes:

 - Subjects are now grouped in separate docs-pages, with a more logical flow
 - Some duplicate example code-samples were removed
 - The implementation coverage script now updates the Github-doc _and_ the RTD page.
 - The list of implemented services on the RTD page now show the Python __doc__ for every service and method. This will make it a lot easier to document feature-specific quirks, such as parameters that are not implemented, available environment variables, etc.

Both the structure and actual content can always be improved of course, so any feedback is welcome.

---------------------

Preview of what the README would look like:
https://github.com/bblommers/moto/tree/improve-docs

Preview of what the RTD would look like:
https://moto--3728.org.readthedocs.build/en/3728/

-------------------------
Future improvements that I've identified so far:
 - Give the CONTRIBUTING-doc the same treatment. It needs much more background information, tips&tricks, etc to be helpful for a first time contributor. Having this info on RTD with a proper hierarchy instead of everything on a single page would help immensely

### CODE REVIEW

**Review by spulec — APPROVED** [review]
This looks great. I like breaking the services out into their own pages.

**Comment by kbalk** [comment]
@bblommers The scaffold script needs updating ...

**Comment by bblommers** [comment]
Thanks @kbalk!

I've updated the scaffold-script in https://github.com/spulec/moto/pull/4543, + a few other minor things..
Running `scripts/implementation_coverage` will now update the docs with new features/services - I've added a note for users to run this script.

**Comment by kbalk** [comment]
@bblommers I saw a reference to the Tagging Service in one of the docs and wondered if you wanted to add anything about the pagination facility?

There's some odd formatting here and there, really minor stuff:

- `development_tips.rst` in the naming conventions section there are vertical bars in the paragraphs.
- `faq.rst` in the "What" section the first question has bold italics in the description; not sure if that's intentional.
- `faq.rst` in the "Why am I getting the error...", the `pip install .` should probably have backslashes to indicate a command.

**Comment by bblommers** [comment]
Appreciated the review @kbalk. I've added/changed all 4 in #4545

**Pull request merged**
