### PR TITLE
Added SSM GetParameter support

### PR DESCRIPTION
**Pull request by terrycain**
SSM now has GetParameter (boto added get_parameter) so I added it here.

Any issues with this?

### CODE REVIEW

**Comment by oharaandrew314** [comment]
Can you add a test case which gets a parameter that does not exist?  This gave me trouble the last time I tried to implement it.

**Comment by oharaandrew314** [comment]
Ah.  I see what I was missing now.

**Comment by JackDanger** [comment]
Great work, @terrycain ! This is super helpful. Welcome to Moto!

**Comment by terrycain** [comment]
No problem, I'll throw you some more PRs if I come across anything else :smile:

**Comment by JackDanger** [comment]
This is now released as part of Moto 1.1.11

**Pull request merged**
