### PR TITLE
Fix custom amis import

### PR DESCRIPTION
**Pull request by rafcio19**
If custom amis are specified via `MOTO_AMIS_PATH` env var, then do not import default amis.

Resolves https://github.com/spulec/moto/issues/5677

### CODE REVIEW

**Comment by bblommers** [comment]
Some context, in case you hadn't seen it yet: all tests in `tests/test_ec2` are [run in parallel](http://docs.getmoto.org/en/latest/docs/contributing/development_tips/tests.html#parallel-tests), to speed things up. So testing this particular feature, and assert we have only one AMI available, is a bit tricky.

I haven't really sat down to think about how to do this - but maybe we can simply run this test from a separate folder, something like `tests/test_ec2_custom_ami/test.py`. That way we can continue running all 'regular' EC2 tests in parallel, and we can be sure that this particular test is always run on it's own, without interference from other tests.

Let me know if you want me to take a closer look.

**Comment by rafcio19** [comment]
Thanks for looking @bblommers . I saw this behaviour when testing locally:

```
 pytest tests/test_ec2/test_*ami*
```

but running these fellas individually works:

```
pytest tests/test_ec2/test_amis.py
pytest tests/test_ec2/test_custom_amis.py
```

I will see if a bit of tinkering with the makefile will help.

**Comment by rafcio19** [comment]
Hey @bblommers this is ready for a review, now lemme know what you think. I changed the `Unit tests in Server Mode` workflow to run the `test_server` make target and the tests pass this way.. 😬

Clearly this changes the CI a little bit but because the "regular" unit tests pass then perhaps it's ok.

**Review by bblommers — APPROVED** [review]
Thanks @rafcio19! I've refactored the test a bit - it now resets and re-imports the EC2-backend after setting the env variable. That way we can remove any existing AMI's, and only load our custom AMI, but without having to worry about running `pytest` multiple times.

**Pull request merged**
