### PR TITLE
do not depend on deprecated nose

### PR DESCRIPTION
**Pull request by pgajdos**
Second attempt, still humble.

### CODE REVIEW

**Comment by pgajdos** [comment]
I think I am out of ideas with these two failures, could you please advise @spulec?

**Comment by pgajdos** [comment]
(Actually, three failures and four for 2.7, respectively.)

**Comment by mcepl** [comment]
Probably replaced by https://github.com/spulec/moto/pull/3361.

**Comment by pgajdos** [comment]
@mcepl No problem. Thanks you care of it!

**Pull request closed without merging**
