### PR TITLE
 S3: Implement CORS headers in OPTIONS requests 

### LINKED ISSUE #4220: Unable to include Access-Control-Expose-Header = "ETag" in CORS response
Hi everyone! I'm using Moto to mock an S3 bucket from an end to end test for a web application. Our tests use something similar to Selenium to control the browser so we're interacting with the Moto standalone server via HTTP.

Moto version: 2.2.2 (Moto standalone server)
How I installed it:
1. sudo apt install python-pip
2. sudo -H pip install "moto[s3]"
3. pip install flask
4. pip install flask_cors

Environment: pipenv with Python 3.8.0 running on an Ubuntu 18.04.5 LTS machine.

The issue is that when uploading a file to the bucket, Moto fails because it can't find the ETag. I've found that the browser refuses to set the ETag on the request because it hasn't received an ExposeHeader on the CORS response.

Here are the steps I'm following:
1. Starting Moto with `moto_server s3 -s -H 0.0.0.0`
2. Creating the bucket with Amazon's S3 SDK in PHP:
 
Screenshot at 2021-08-25 16-08-50

3. Adding the CORS configuration to the bucket. For some reason Amazon's SDK is stripping the "ExposedHeader" from the PutBucketCors (I added some prints to check and it's not reaching Moto) so for now I'm sending it via CURL. Here's the request and how Moto shows the rule in /moto-api:

postman_curl
moto_api

4. Uploading the file from the web application that we want to test. It uses EvaporateJS to communicate with Amazon, so I changed it to point to Moto. Here's the preflight request:

preflight

You can see that there's no Expose-Header on the response, so on the next request the browser refuses to set the ETag. This causes Moto to fail with the following stack:

```10.0.6.1 - - [25/Aug/2021 19:18:30] "POST /mytestbucket/temp/8a6dc338bf4d974cbc68c204f1e42f16586b9fd454dc2a57995e920fe989ff30?uploadId=LwLkW061R0WHC0Jsgx1xhZWsfXeCpfvY5kycVGgUnhKUD5UtIaqsB5n2JQ HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/home/sb-3/.local/share/virtualenvs/moto-ol9WsJxn/lib/python3.8/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/home/sb-3/.local/share/virtualenvs/moto-ol9WsJxn/lib/python3.8/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/home/sb-3/.local/share/virtualenvs/moto-ol9WsJxn/lib/python3.8/site-packages/moto/server.py", line 181, in __call__
    return backend_app(environ, start_response)
  File "/home/sb-3/.local/share/virtualenvs/moto-ol9WsJxn/lib/python3.8/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/sb-3/.local/share/virtualenvs/moto-ol9WsJxn/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/home/sb-3/.local/share/virtualenvs/moto-ol9WsJxn/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/sb-3/.local/share/virtualenvs/moto-ol9WsJxn/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sb-3/.local/share/virtualenvs/moto-ol9WsJxn/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sb-3/.local/share/virtualenvs/moto-ol9WsJxn/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/sb-3/.local/share/virtualenvs/moto-ol9WsJxn/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sb-3/.local/share/virtualenvs/moto-ol9WsJxn/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/sb-3/.local/share/virtualenvs/moto-ol9WsJxn/lib/python3.8/site-packages/moto/core/utils.py", line 148, in __call__
    result = self.callback(request, request.url, {})
  File "/home/sb-3/.local/share/virtualenvs/moto-ol9WsJxn/lib/python3.8/site-packages/moto/s3/responses.py", line 1005, in key_or_control_response
    response = self._key_response(request, full_url, headers)
  File "/home/sb-3/.local/share/virtualenvs/moto-ol9WsJxn/lib/python3.8/site-packages/moto/s3/responses.py", line 1176, in _key_response
    return self._key_response_post(request, body, bucket_name, query, key_name)
  File "/home/sb-3/.local/share/virtualenvs/moto-ol9WsJxn/lib/python3.8/site-packages/moto/s3/responses.py", line 1792, in _key_response_post
    value, etag = multipart.complete(body)
  File "/home/sb-3/.local/share/virtualenvs/moto-ol9WsJxn/lib/python3.8/site-packages/moto/s3/models.py", line 314, in complete
    for pn, etag in body:
  File "/home/sb-3/.local/share/virtualenvs/moto-ol9WsJxn/lib/python3.8/site-packages/moto/s3/responses.py", line 1766, in _complete_multipart_body
    yield (pn, p.getElementsByTagName("ETag")[0].firstChild.wholeText) 
AttributeError: 'NoneType' object has no attribute 'wholeText' 
```

I've searched the existing issues but found nothing quite matching this. I can avoid the problem entirely if I just change the part of moto/server.py (line 222) that adds CORS with flask_cors from `CORS(backend_app)` to `CORS(backend_app, expose_headers="ETag")` but I suspect that it isn't the right way to go.

It looks like the CORS rule I set isn't being applied when responding to the preflight request. I'm not sure if this is an actual bug, I don't have a ton of experience with HTTP and CORS so I might be missing something. Any help is greatly appreciated.

Thank you all in advance.

### PR DESCRIPTION
**Pull request by vbarbaresi**
Hacktoberfest contribution 🎃 

Fixes #4220 

The default headers from CORS plugin was not enough to mock S3 CORS Rules behavior
We need to manually define response headers depending on the bucket rules

- Fixed typos:
  -  `ExposedHeader` --> `ExposeHeader` (defined as such in AWS documentation)
  - `MaxAgeSecond` --> `MaxAgeSeconds`(defined as such in AWS documentation)
- I implemented OPTIONS method instead of relying on the defaults from Flask

- Iterated through CORS rule to return some CORS headers
This is not a perfectly accurate strategy: I didn't check but according to the docs, when multiple CORS Rules are defined, S3 returns the most relevant (I suppose the most permissive one, depending on the request)
In the strategy I implemented, the last rule takes precedence over the other rules.
It's not ideal but I consider that defining multiple rules is an edge case

- Removed a test about `Allow` headers: these headers were automatically set by flask-cors but they are not technically CORS?
I didn't add these headers back because they are not required and from my testing on a real S3 bucket, I didn't receive any `Allow` header, only `Access-Control-Allow-Methods`

### CODE REVIEW

**Comment by vbarbaresi** [comment]
I managed to fix the tests

I edited the description, I added back copying the `request.headers` into the response headers in a slightly different form:

```python
self.headers = dict(request.headers)
```
I copied the headers object into a dict object. It lost some of its "magic" properties like case-insensitivity.
So `"host" in self.headers` had to be changed to `"Host" in self.headers`

**Review by bblommers — APPROVED** [review]
LGTM! Thanks for the fixes

**Comment by ivb-supercede** [comment]
This PR broke our use of Moto's standalone server for mocking S3. Prior to the first commit, we were able to upload to a Moto S3 instance from the browser - afterwards, we get a CORS error in the browser when trying to upload, and Moto's request handler fails with:
```
Error on request:
Traceback (most recent call last):
...
  File "/home/ivanbakel/.local/share/virtualenvs/moto-oItiPM7T/lib/python3.9/site-packages/moto/s3/responses.py", line 1110, in key_or_control_response
    response = self._key_response(request, full_url, self.headers)
  File "/home/ivanbakel/.local/share/virtualenvs/moto-oItiPM7T/lib/python3.9/site-packages/moto/s3/responses.py", line 1298, in _key_response
    raise NotImplementedError(
NotImplementedError: Method OPTIONS has not been implemented in the S3 backend yet
```

**Comment by vbarbaresi** [comment]
Would you have a snippet reproducing the issue ? I think I see what's going on but I'd like to make sure I can fully fix your use case
I forgot to add OPTIONS method handling in `_key_response()`: https://github.com/spulec/moto/blob/ccd216dfe5d34bef5bf2fe2268a2ccf603255b73/moto/s3/responses.py#L1298

**Comment by ivb-supercede** [comment]
I don't know enough to be able to produce a snippet. We're using jQuery's AJAX functionality to do uploads from the browser.

Here's the meat of our upload code:
```javascript
// This function also handles the case where the file is a blob part
function uploadFileTo(file, url, onProgress, shouldAddTags) {
  function setupXhrListener() {
    var xhr = $.ajaxSettings.xhr();
    if (!xhr || !xhr.upload) { return; }

    // For handling the progress of the upload
    xhr.upload.addEventListener('progress', function (e) {
      onProgress && onProgress(e.loaded, e.total);
    }, false);

    return xhr;
  }

  return new Promise(function (resolve, reject) {
    $.ajax({
      url: url,
      method: 'PUT',
      headers: {},
      cache: false,
      contentType: file.type,
      processData: false,
      data: file,
      error: function () { reject(); },
      success: function (data, status, jqXhr) {
        // The ETag header is enclosed in quotes so we slice them off
        resolve((jqXhr.getResponseHeader('ETag') || '').slice(1, -1));
      },
      xhr: setupXhrListener
    });
  });
}
```

I am set up to run whatever commit of Moto as a mock for our uploader, so I'm happy to act as a tester if you're able to come up with a prototype solution.

**Comment by vbarbaresi** [comment]
Could you try if https://github.com/spulec/moto/pull/4528 solves the issue?

**Comment by ivb-supercede** [comment]
Yep, the PR commit works for me when testing locally!

**Pull request merged**
