### PR TITLE
Fix/autoscaling elb interaction

### PR DESCRIPTION
**Pull request by gipi**
This is a first attempt to fix issue #3748 in a pretty hacky way: in the original code the assumption is that all the instances attached to a load balancer are only by an autoscaling group, so when the group is modified it acts on the load balancer so to have only its own instances attached, but this is not how the ELB behaves, you can manually attach isolated machines that remain independent by the group.

For now I'm using an internal attribute to take note of which instances are intended to be deregistered from the load balancer but I'm pretty sure it's not a very good way of do it, maybe I'm missing some subtle point about instances, however the tests seem to pass. So if someone more experienced with the code want to give me feedback I can try to improve it.

I also improved a test to catch the bug, if it's ok I'm going to extend to other tests involving this service.

### CODE REVIEW

**Review by bblommers — CHANGES_REQUESTED** [review]
Hi @gipi, thanks for the PR!
IMO this would be cleaner if we store two separate sets of instance_ids per ELB. One set of 'native' instances, registered directly, and one set of instances controlled by the ASG. 
The autoscaling-service will only have to touch the ASG-controlled instances, and we don't have to worry about accidentally removing any instances it doesn't have control over.

**Comment by gipi** [comment]
@bblommers ok makes sense but this means we should create two separate "family" of de/register calls, one for group and one for the other in the ELB and to me seems a big change.

**Comment by bblommers** [comment]
I'd be in favor of the keyword argument. As long as it has a sensible default, and the only change is in models.py, there should be no impact.

**Comment by gipi** [comment]
I tried the new approach; it needs some adjustments but seems cleaner than before: I split the instance ids in "sparse" (probably a better naming would be "native") and "from autoscaling group" and added the ``from_autoscaling`` as a keyword argument in the necessary methods.

**Review by bblommers — CHANGES_REQUESTED** [review]
Thanks for the reminder @gipi. The ServerMode tests are failing, probably because of the fact that the tests now combine `deprecated` and normal decorators.
Might have to rewrite the test to use only deprecated, or only normal, decorators

**Review by bblommers — APPROVED** [review]
LGTM! Thanks @gipi

**Pull request merged**
