### PR TITLE
Fix dev versions

### PR DESCRIPTION
**Pull request by flying-sheep**
You’re using versions wrong, [see PEP 440](https://www.python.org/dev/peps/pep-0440/#developmental-releases).

> The developmental release segment consists of the string .dev, followed by a non-negative integer value. Developmental releases are ordered by their numerical component, **immediately before the corresponding release** […]

i.e.: `1.3.16.devX` < `1.3.16`

This PR uses proper types for the version code which compare correctly. 
An alternative to `1.3.17.devX` would be to use `1.3.16.postX`, which would properly sort as newer than `1.3.16`

The order on PyPI demonstrates that `1.3.16.devX` releases sort as older than `1.3.16`:

grafik

### CODE REVIEW

**Review by andersk — APPROVED** [review]
This fix is important for those who need to depend on `moto>=1.3.16.dev122` because of #3460, but then get “upgraded” back to `1.3.16`. Please merge.

**Comment by andersk** [comment]
Could be marked as Fixes: #3478.

**Review by bblommers — CHANGES_REQUESTED** [review]
Hi @flying-sheep, this change generates a version in an invalid format:
`1.3.17.dev0.172`

I've updated the version manually for now, to unblock people - 1.3.17.dev221 is the first properly named release.

**Comment by flying-sheep** [comment]
@bblommers fixed! Too bad `Version`s are immutable, otherwise the code could have been sth. clean like:

```py
dev_version = init_version.copy()
dev_version.dev = commits_since
return dev_version
```

**Comment by bblommers** [comment]
Closing this in favor of #4016

**Pull request closed without merging**
