### PR TITLE
Allow mock_s3 to use the standalone moto server running in alternative endpoint by adding TEST_SERVER_MODE_ENDPOINT environment variable

### PR DESCRIPTION
**Pull request by ikkala**
Before this, the ServerMode (TEST_SERVER_MODE=true) endpoint has been hardcoded to `http://localhost:5000`. If MotoServer runs in different endpoint than `http://localhost:5000`, for example in case when the it runs in separate Docker container, the tests are failing.

This pull request makes the previously hardcoded value as default value for new `TEST_SERVER_MODE_ENDPOINT` environment variable.  If MotoServer runs in different endpoint than `http://localhost:5000` the endpoint can be overridden by using `TEST_SERVER_MODE_ENDPOINT` environment variable.

Example usage in docker-compose.yml:

```
  moto-server:
    image: motoserver/moto:2.2.11

  test:
    build:
      context: packages/tests/
      dockerfile: Dockerfile_tests
    depends_on:
      - moto-server
    environment:
      TEST_SERVER_MODE: 'true'
      TEST_SERVER_MODE_ENDPOINT: http://moto-server:5000
      AWS_ENDPOINT_URL: http://moto-server:5000
```

In addition, this pull requests fixes error in documentation: It was saying erroneously that `MOTO_CALL_RESET_API=true` keeps the state in between tests.

### CODE REVIEW

**Comment by ikkala** [comment]
This pull requested was inspired by discussion in https://github.com/spulec/moto/issues/4418 ("Allow mock_s3 to use the standalone moto server").

**Comment by bblommers** [comment]
Hi @ikkala, this makes a lot of sense, to make this endpoint configurable. There is already a PR outstanding with some changes in this area, #4658. I'll have another look here once that is merged.

**Comment by ikkala** [comment]
Ok, excellent!  Nice to hear that there's related work going on. 

I tried to skim through similar issues and pull requests but didn't find anything that changes also the host name.  For example, looks like that the #4658 only makes the port variable: https://github.com/spulec/moto/pull/4658/files#diff-3ed8c52a492672972d143cfc55b9d3a6024396b00ab554538b72c01b46948430R522
So, I decided to make this pull request.

This pull request change is already in use in our integration tests that have been put together by using Docker Compose, as described in "Example usage in docker-compose.yml" above, so it works. But, it's only for testing of S3 bucket handling, so it might of course miss something that should be added for make it work in all scenarios.

**Comment by ikkala** [comment]
Hi @bblommers again, looks like you have now merged the #4658 changes -- you make lots of work for moto, thank you!  :+1: 

I adapted this PR changes to the latest master trunk. Would it be ready for merge in near future..?

**Review by bblommers — APPROVED** [review]
LGTM! Thanks again for the PR @ikkala

**Pull request merged**
