### PR TITLE
Databrew: Add datasets support

### PR DESCRIPTION
**Pull request by SteveChurch**
Adds dataset(s) support for databrew

This includes these additional methods:

`update_dataset()`
`list_datasets()`
`describe_dataset()`
`delete_dataset()`
`create_dataset()`

### CODE REVIEW

**Review by bblommers — CHANGES_REQUESTED** [review]
Hi @SteveChurch, thanks for the PR! The `coverage.xml` file should not be part of the commit, and it looks like the linter is failing as well.

**Comment by SteveChurch** [comment]
> Hi @SteveChurch, thanks for the PR! The `coverage.xml` file should not be part of the commit, and it looks like the linter is failing as well.

Thanks, I will get this resolved now. 👍🏻 - Am I safe to update the PR directly on this repo or should make changes against our Fork?

@bblommers

**Comment by SteveChurch** [comment]
@bblommers I will do a rebase after #5094 has been merged.

**Comment by bblommers** [comment]
@SteveChurch Could you also add a test to verify what happens when updating an unknown dataset? That error scenario has not been covered yet. Other than that, it all looks good to me.

**Comment by SteveChurch** [comment]
> @SteveChurch Could you also add a test to verify what happens when updating an unknown dataset? That error scenario has not been covered yet. Other than that, it all looks good to me.

Rebase done and new test added as requested.

**Comment by SteveChurch** [comment]
> The `coverage.xml` is back @SteveChurch - looks like the linter is failing as well

:face-palm: - Fixing now. Sorry.

**Comment by SteveChurch** [comment]
@bblommers the linter fails in your jobs, but it doesn't make any changes when I run `make lint` or `make format`

**Comment by bblommers** [comment]
> @bblommers the linter fails in your jobs, but it doesn't make any changes when I run `make lint` or `make format`

Which version of flake8 are you on? We've upgraded fairly recently to `4.0.1`, so that may explain the difference. 

Looks like there is only one flake8 issue though, so you can resolve it without running `make lint` locally if necessary:
https://github.com/spulec/moto/runs/6366879467?check_suite_focus=true

**Comment by SteveChurch** [comment]
> > @bblommers the linter fails in your jobs, but it doesn't make any changes when I run `make lint` or `make format`
> 
> Which version of flake8 are you on? We've upgraded fairly recently to `4.0.1`, so that may explain the difference.
> 
> Looks like there is only one flake8 issue though, so you can resolve it without running `make lint` locally if necessary: https://github.com/spulec/moto/runs/6366879467?check_suite_focus=true

Right you are @bblommers ! I was on 3.7. Done and raring to go :D

**Review by bblommers — APPROVED** [review]
Awesome - thanks for all your work on this @SteveChurch!

**Pull request merged**
