### PR TITLE
RDS Filtering on db-cluster-id

### PR DESCRIPTION
**Pull request by mattBrzezinski**
Fixes: https://github.com/spulec/moto/issues/5091

### CODE REVIEW

**Comment by mattBrzezinski** [comment]
@bblommers I updated the Database templates to return back cluster identifiers, should be good for another run now.

**Comment by mattBrzezinski** [comment]
@bblommers forgot to set the cluster in `setup_class()` when testing, should be good now? 🤞

**Comment by mattBrzezinski** [comment]
Seems good to go now, let me know if there's anything else you'd like here.

**Review by bblommers — APPROVED** [review]
LGTM - thanks for implementing this @mattBrzezinski!

**Pull request merged**
