### PR TITLE
Dynamodb expressions parser

### LINKED ISSUE #1819: FilterExpression Key condition "between" on String values results in ValueError
When query table using FilterExpression Key condition "between" with String values results in ValueError thrown. On actual AWS dynamodb table the code works fine.

**Sample code to reproduce error**
```
import boto3, os, unittest, moto
from decimal import *
from boto3.dynamodb.conditions import Key

@moto.mock_dynamodb2

class TestDynamoDb(unittest.TestCase):

	def test_dynamo_db(self):
		self.mock_table()
		self.mock_data()
		self.search_for_flights_between_dates('GDN', 'STN', '2018-08-07T00:00:00+00:00', '2018-08-09T00:00:00+00:00')

	@staticmethod
	def dynamo_db_resource():
		return boto3.resource('dynamodb', region_name='eu-west-2')

	@staticmethod
	def dynamo_db_table():
		return TestDynamoDb.dynamo_db_resource().Table("flights_table_test")

	def mock_table(self):
		TestDynamoDb.dynamo_db_resource().create_table(
			AttributeDefinitions = [
			    {
			        "AttributeName": "flight_identifier",
			        "AttributeType": "S"
			    },
			    {
			        "AttributeName": "from_airport_iata_code",
			        "AttributeType": "S"
			    },
			    {
			        "AttributeName": "price",
			        "AttributeType": "N"
			    },
			    {
			        "AttributeName": "start_date_timestamp",
			        "AttributeType": "S"
			    },
			    {
			        "AttributeName": "to_airport_iata_code",
			        "AttributeType": "S"
			    }
			],
			TableName = "flights_table_test",
			KeySchema = [
			    {
			        "AttributeName": "from_airport_iata_code",
			        "KeyType": "HASH"
			    },
			    {
			        "AttributeName": "flight_identifier",
			        "KeyType": "RANGE"
			    }
			],
			ProvisionedThroughput = {
			    "ReadCapacityUnits": 2,
			    "WriteCapacityUnits": 4
			},
			LocalSecondaryIndexes = [
			    {
			        "IndexName": "from_airport_iata_code-start_date_timestamp-index",
			        "KeySchema": [
			            {
			                "AttributeName": "from_airport_iata_code",
			                "KeyType": "HASH"
			            },
			            {
			                "AttributeName": "start_date_timestamp",
			                "KeyType": "RANGE"
			            }
			        ],
			        "Projection": {
			            "ProjectionType": "ALL"
			        },
			    },
			    {
			        "IndexName": "from_airport_iata_code-to_airport_iata_code-index",
			        "KeySchema": [
			            {
			                "AttributeName": "from_airport_iata_code",
			                "KeyType": "HASH"
			            },
			            {
			                "AttributeName": "to_airport_iata_code",
			                "KeyType": "RANGE"
			            }
			        ],
			        "Projection": {
			            "ProjectionType": "ALL"
			        },
			    },
			    {
			        "IndexName": "from_airport_iata_code-price-index",
			        "KeySchema": [
			            {
			                "AttributeName": "from_airport_iata_code",
			                "KeyType": "HASH"
			            },
			            {
			                "AttributeName": "price",
			                "KeyType": "RANGE"
			            }
			        ],
			        "Projection": {
			            "ProjectionType": "ALL"
			        },
			    }
			]
		)

	def mock_data(self):
		TestDynamoDb.dynamo_db_table().put_item(
			Item= {
				'flight_identifier' : 'FR1691GDNAAR2018-08-05',
				'price': Decimal(200.0),
				'start_date_timestamp': '2018-08-05T00:00:00+00:00',
				'currency': 'PLN',
				'from_airport_string': 'Gdansk',
				'to_airport_string' : 'Stanford',
				'from_airport_iata_code': 'GDN',
				'to_airport_iata_code' : 'STN'
			}
		)

		TestDynamoDb.dynamo_db_table().put_item(
			Item= {
				'flight_identifier' : 'FR1691GDNAAR2018-08-07',
				'price': Decimal(100.0),
				'start_date_timestamp': '2018-08-07T00:00:00+00:00',
				'currency': 'PLN',
				'from_airport_string': 'Gdansk',
				'to_airport_string' : 'Stanford',
				'from_airport_iata_code': 'GDN',
				'to_airport_iata_code' : 'STN'
			}
		)

		TestDynamoDb.dynamo_db_table().put_item(
			Item= {
				'flight_identifier' : 'FR1691GDNAAR2018-08-09',
				'price': Decimal(105.0),
				'start_date_timestamp': '2018-08-09T00:00:00+00:00',
				'currency': 'PLN',
				'from_airport_string': 'Gdansk',
				'to_airport_string' : 'Stanford',
				'from_airport_iata_code': 'GDN',
				'to_airport_iata_code' : 'STN'
			}
		)


	def search_for_flights_between_dates(self, iata1, iata2, date1, date2):
		return TestDynamoDb.dynamo_db_table().query(
				IndexName="from_airport_iata_code-to_airport_iata_code-index",
				KeyConditionExpression=(Key('from_airport_iata_code').eq(iata1) & Key('to_airport_iata_code').eq(iata2)),
				FilterExpression=Key('start_date_timestamp').between(date1, date2)
			)

```

**Expected result**
Query should return items filtered by dates used in "between" condition

**Actual error:**
`ValueError: invalid literal for int() with base 10: '2018-08-07T00:00:00+00:00'`

**Full stack trace**
```
======================================================================
ERROR: test_flights_db_get_flight_from_airport_to_airport_between_dates (naviaflightsdb_tests.workers.tests.flights_db_worker_tests.WorkerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "/Users/piotrolechnowicz/naviadev/naviaflightsdb/naviaflightsdb/naviaflightsdb_tests/workers/tests/flights_db_worker_tests.py", line 75, in test_flights_db_get_flight_from_airport_to_airport_between_dates
    response = databaseWorker.getFlights('GDN', 'AAR', datetime(2018, 8, 6), datetime(2018, 8, 7))
  File "/Users/piotrolechnowicz/naviadev/naviaflightsdb/naviaflightsdb/naviaflightsdb/workers/db/flights_db_worker.py", line 23, in getFlights
    return FlightsdbQueryExecutor.execute(query);
  File "/Users/piotrolechnowicz/naviadev/naviaflightsdb/naviaflightsdb/naviaflightsdb/workers/executors/db/flights_db_query_executor.py", line 21, in execute
    response = query.execute_on_table(table)
  File "/Users/piotrolechnowicz/naviadev/naviaflightsdb/naviaflightsdb/naviaflightsdb/queries/flights_db_get_flights_query.py", line 39, in execute_on_table
    FilterExpression=self.filter_expression()
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/botocore/client.py", line 599, in _make_api_call
    operation_model, request_dict)
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/botocore/endpoint.py", line 148, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/botocore/endpoint.py", line 177, in _send_request
    success_response, exception):
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/botocore/endpoint.py", line 273, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/botocore/hooks.py", line 360, in _emit
    aliased_event_name, kwargs, stop_on_response
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/botocore/endpoint.py", line 222, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/responses.py", line 572, in unbound_on_send
    return self._on_request(adapter, request, *a, **kwargs)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/responses.py", line 548, in _on_request
    match.get_response(request), )
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/moto/core/models.py", line 137, in get_response
    result = self.callback(request)
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/moto/core/utils.py", line 172, in __call__
    result = self.callback(request, request.url, request.headers)
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/moto/core/responses.py", line 117, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/moto/core/responses.py", line 200, in _dispatch
    return self.call_action()
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/moto/core/utils.py", line 263, in _wrapper
    response = f(*args, **kwargs)
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/moto/dynamodb2/responses.py", line 53, in call_action
    response = getattr(self, endpoint)()
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/moto/dynamodb2/responses.py", line 433, in query
    filter_expression=filter_expression, **filter_kwargs
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/moto/dynamodb2/models.py", line 778, in query
    filter_expression = get_filter_expression(filter_expression, expr_names, expr_values)
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/moto/dynamodb2/comparisons.py", line 201, in get_filter_expression
    handle_token(token, tokens2, token_iterator)
  File "/Users/piotrolechnowicz/Library/Python/3.6/lib/python/site-packages/moto/dynamodb2/comparisons.py", line 167, in handle_token
    op1 = int(values_map.get(op1, op1))
ValueError: invalid literal for int() with base 10: '2018-08-06T00:00:00+00:00'

```

Library versions
moto : 1.3.5
boto3 : 1.7.84

### PR DESCRIPTION
**Pull request by mjstevens777**
This PR improves condition expression support for dynamodb2. It should hopefully fix #1819, #1587, and #1711.

The essential changes are:
- Update the parsing code for filter expressions to an OOP design that is hopefully more readable and reliable
- Add some test cases for condition expressions that were previously not implemented
- Support nested attributes in List and Map types.
- Switch `Expected` to use the code in `comparisons`
- Switch `ConditionExpression` to use code in `comparisons` as well

The remaining TODO items are
- [x] Finish adding test cases
- [ ] Finish documenting
- [x] Update uses of `super()` to support python 2
- [ ] DRY up the code for `DynamoType` and `AttributeValue`

### CODE REVIEW

**Comment by killthrush** [comment]
Thanks for doing this work @mjstevens777!  I'd be happy to pull it down and test it with some use cases I have.  Is it in a state where I can do that?

**Comment by mjstevens777** [comment]
@killthrush It should be ready to use. The tests are now passing for both python2 and python3.

**Comment by killthrush** [comment]
Cool.  So I got this to work with several use cases.  There was on particular one related to attribute names that I couldn't get to work - this case should raise an exception if I run it more than once but it doesn't:

```
new_state = 'starting'
result = table.update_item(Key={'job_id': job_id},
                           UpdateExpression='SET #new_state=:new_state',
                           ConditionExpression='attribute_not_exists(#new_state)',
                           ExpressionAttributeNames={
                               '#new_state': new_state,
                           },
                           ExpressionAttributeValues={
                               ':new_state': 123,
                           },
                           ReturnValues='ALL_NEW')
```
If I do this, then the ConditionExpression *does* work as expected and the mock raises an exception:

```
new_state = 'starting'
result = table.update_item(Key={'job_id': job_id},
                           UpdateExpression='SET #new_state=:new_state',
                           ConditionExpression=f'attribute_not_exists({new_state})',
                           ExpressionAttributeNames={
                               '#new_state': new_state,
                           },
                           ExpressionAttributeValues={
                               ':new_state': 123,
                           },
                           ReturnValues='ALL_NEW')
```

I'm pretty sure that attribute names should be honored in these expressions, is that your understanding as well?

**Comment by mjstevens777** [comment]
@killthrush It looks like there were no tests for `update_item` with `ConditionExpression`, so that was a helpful thing to point out. But it looks like the tests are correctly throwing errors with `update_item`, `attribute_not_exists`, and `ExpressionAttributeNames`, so I'm not sure what the issue would be.

**Comment by killthrush** [comment]
🤔 Interesting.  It's still failing for me over here with 6ae3ac6.  I'll fork your repo and see if I can reproduce it there.

**Comment by killthrush** [comment]
OK, reproduced in the test fixture with the following:
```
    # Test nonexistent top-level attribute.
    with assert_raises(client.exceptions.ConditionalCheckFailedException):
        table.update_item(Key={
            'forum_name': 'the-key',
            'subject': '123'
            },
            UpdateExpression='set #new_state=:new_state, #ttl=:ttl',
            ConditionExpression=f'attribute_not_exists(#new_state)',
            ExpressionAttributeNames={'#new_state': 'foobar', '#ttl': 'ttl'},
            ExpressionAttributeValues={':new_state': 'some-value', ':ttl': Decimal('12345.67')},
            ReturnValues='ALL_NEW'
        )
```

**Comment by garrettheel** [comment]
@mjstevens777 are you still working on this or is it fair game for me to pick it up?

**Comment by mjstevens777** [comment]
I’m not really working on it. That would be great, thanks!

**Comment by spulec** [comment]
Closing in favor of https://github.com/spulec/moto/pull/2266

**Pull request closed without merging**
