### PR TITLE
#3667: Update the s3 post functionality to better support success_action_redirect

### PR DESCRIPTION
**Pull request by wynnw**
…irect

- Add the bucket/key values to the redirect url like s3 does, which
supports code that relies on the key value being there on the
redirect.
- Add support for replacing ${filename} in the key value with the actual
filename from the form upload.

See Issue #3667

### CODE REVIEW

**Comment by wynnw** [comment]
The tests aren't passing on this, but they aren't on the standard master branch either without my commit. Hangs in the test_lambda.py code after 4 failures.

**Review by bblommers — CHANGES_REQUESTED** [review]
Hi @wynnw, thanks for your PR!

The tests might be failing locally because you don't have docker running/installed.
The only CI test that is failing is `test_creating_presigned_post`, because it's doesn't expect the Location-header to have the new bucket/key parameters.

Would be good to have a new unit test for the `${filename}` change as well

**Comment by wynnw** [comment]
I just pushed up a commit to address those test issues.

I've got docker configured and running but still can't get all the tests to pass. Sounds like they are for you though? This latest commit should fix the test failure you mentioned.

**Comment by wynnw** [comment]
Well this passed so I think I've got it. Sorry for the python2.7 breakage churn, but it looks all good now.

**Review by bblommers — APPROVED** [review]
LGTM @wynnw. Thanks for making the changes!

**Comment by wynnw** [comment]
Thanks for the reviews and working with me on this. This allows us to write some really great integration tests that have been missing for us.

**Pull request merged**
