### PR TITLE
moto: s3: support partNumber for head_object

### LINKED ISSUE #2154: head-object for specific part returns ContentLength for the whole object
If an object is uploaded as a multipart, head-object with `PartNumber=1` set should return ContentLength for that part and not for the whole object. Here is a test that shows that with regular s3 ContentLength for a particular part is correct and with moto it is equal to the size of the whole object.

```
import uuid             
import boto3            
from moto import mock_s3


BUCKET = "dvc-test"                                                            
                                                                               
                                                                               
def _upload_multipart(s3, Bucket, Key):                                        
    mpu = s3.create_multipart_upload(Bucket=Bucket, Key=Key)                   
    mpu_id = mpu["UploadId"]                                                   
                                                                               
    parts = []                                                                 
    n_parts = 10                                                             
    for i in range(1, n_parts + 1):                                            
        # NOTE: Generation parts of variable size. Part size should be at      
        # least 5MB:                                                           
        # https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadComplete.html
        part_size = 5 * 1024 * 1024                                            
        body = str(i) * part_size                                              
        part = s3.upload_part(                                                 
            Bucket=Bucket,                                                     
            Key=Key,                                                           
            PartNumber=i,                                                      
            UploadId=mpu_id,                                                   
            Body=body,                                                         
            ContentLength=len(body),                                           
        )                                                                      
        parts.append({"PartNumber": i, "ETag": part["ETag"]})                  
                                                                               
    s3.complete_multipart_upload(                                              
        Bucket=Bucket,                                                         
        Key=Key,                                                               
        UploadId=mpu_id,                                                       
        MultipartUpload={"Parts": parts},                                      
    )                                                                          
                                                                               
    for i in range(1, n_parts + 1):                                            
        obj = s3.head_object(Bucket=Bucket, Key=Key, PartNumber=i)             
        assert obj["ContentLength"] == part_size                               
                                                                               
                                                                               
def _test():                                                                   
    session = boto3.session.Session(region_name="us-east-2")                   
    s3 = session.client("s3")                                                  
    Key = str(uuid.uuid4)                                                      
    _upload_multipart(s3, BUCKET, Key)                                         
                                                                               
                                                                               
def test_orig():                                                               
    _test()                                                                    
                                                                               
                                                                               
@mock_s3                                                                       
def test_moto():                                                               
    s3 = boto3.resource("s3")                                                  
    s3.create_bucket(Bucket=BUCKET)                                            
    _test()                                                                    
```

which, when ran with `pytest`, raises:

```
_________________________________________________ test_moto ________________________________________[14/1943]

    @mock_s3
    def test_moto():
        s3 = boto3.resource('s3')
        s3.create_bucket(Bucket=BUCKET)
>       _test()

test_moto.py:59:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test_moto.py:48: in _test
    _upload_multipart(s3, BUCKET, Key)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

s3 = <botocore.client.S3 object at 0x7f94f4b21b38>, Bucket = 'dvc-test'
Key = '<function uuid4 at 0x7f94fe139268>'

    def _upload_multipart(s3, Bucket, Key):
        mpu = s3.create_multipart_upload(Bucket=Bucket, Key=Key)
        mpu_id = mpu["UploadId"]
    
        parts = []
        n_parts = 10
        for i in range(1, n_parts + 1):
            # NOTE: Generation parts of variable size. Part size should be at
            # least 5MB:
            # https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadComplete.html
            part_size = 5*1024*1024
            body = str(i)*part_size
            part = s3.upload_part(
                Bucket=Bucket,
                Key=Key,
                PartNumber=i,
                UploadId=mpu_id,
                Body=body,
                ContentLength=len(body),
    
            )
            parts.append({"PartNumber": i, "ETag": part["ETag"]})
    
        s3.complete_multipart_upload(
            Bucket=Bucket,
            Key=Key,
            UploadId=mpu_id,
            MultipartUpload={"Parts": parts},
        )
    
        for i in range(1, n_parts + 1):
            obj = s3.head_object(Bucket=Bucket, Key=Key, PartNumber=i)
>           assert obj["ContentLength"] == part_size
E           assert 57671680 == 5242880

test_moto.py:41: AssertionError
```

I've scanned through the moto's code, but wasn't able to find the place where this happens. If you could direct me where to look, I will be happy to submit a PR to fix this.

Additional info:

```
(3.7.0-dvc) ➜  dvc git:(fix-1410) ✗ python --version
Python 3.7.0
(3.7.0-dvc) ➜  dvc git:(fix-1410) ✗ pip freeze | grep boto
You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
boto==2.49.0
boto3==1.9.115
botocore==1.12.117
(3.7.0-dvc) ➜  dvc git:(fix-1410) ✗ pip freeze | grep moto
You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
moto==1.3.7
```

Thanks for creating such an amazing project! :slightly_smiling_face:

### PR DESCRIPTION
**Pull request by efiop**
To support it, we need to keep multipart info in the key itself when
completing multipart upload.

Fixes #2154

Signed-off-by: Ruslan Kuprieiev <ruslan@iterative.ai>

### CODE REVIEW

**Comment by spulec** [comment]
This looks great! Thank you!

**Comment by efiop** [comment]
@spulec Is there any ETA for the next release? :slightly_smiling_face:

**Comment by spulec** [comment]
We have continuous prereleases setup so you should be able to install this now: https://pypi.org/project/moto/#history

**Comment by efiop** [comment]
@spulec Oh, didn't know that! Thank you!

**Pull request merged**
