### PR TITLE
Save the sns messages in the PlatformEndpoint

### PR DESCRIPTION
**Pull request by mvantellingen**
This makes it easier to test the correct sns messages are sent.

For example in my test cases I can now do:

```python
    from moto.sns.models import sns_backends
    messages = sns_backends['eu-west-1'].platform_endpoints.values()[0].messages
    
    # check number of messages
    assert len(messages) == 1
    assert 'Hello' in messages.values()[0]
```

### CODE REVIEW

**Comment by spulec** [comment]
thanks!

**Comment by tzusman** [comment]
@mvantellingen Is it possible to read these messages when moto is in server mode?

**Comment by bblommers** [comment]
Hi @tzusman, it is of course possible to use the `receive_message` to verify whether a message has been sent.
Directly accessing the backend to read the messages is not possible at the moment, though.

Slightly related feature request: https://github.com/spulec/moto/issues/2882

**Comment by tzusman** [comment]
Hey @bblommers thanks for getting back to me.  I just wanted to confirm that you're talking about using SQS's receive_message to get these push notification payloads?  It doesn't look like the messages are being published anywhere, but rather just [stored in the Dict](https://github.com/spulec/moto/blob/master/moto/sns/models.py#L346)

**Comment by bblommers** [comment]
Ah, my bad @tzusman - I misread it as SQS. You're right, in that case, the SNS messages are not published anywhere.

**Comment by tzusman** [comment]
I had to hack it (now it sends an http request whenever a message is sent to a PlatformEndpoint).  Obviously this is less than ideal.  @bblommers what do you think would be the least dirty way of pulling that `messages` data out in server mode?

**Comment by bblommers** [comment]
@tzusman Probably a custom HTTP endpoint in the MotoServer to download the internal state, with filters to retrieve the state of a specific service. 
That would be the most generic solution, and usable for any language/platform/service.

**Pull request merged**
