### PR TITLE
Fix SQS send_message_batch empty array Exception handling

### PR DESCRIPTION
**Pull request by usmangani1**
https://github.com/localstack/localstack/issues/1658

Fix SQS send_message_batch empty array Exception handling

### CODE REVIEW

**Comment by usmangani1** [comment]
> [localstack/localstack#1658](https://github.com/localstack/localstack/issues/1658)
> 
> Fix SQS send_message_batch empty array Exception handling

@bblommers Need your help in getting this small change merged.

**Comment by spulec** [comment]
Looks great; thanks and welcome to Moto!

**Comment by usmangani1** [comment]
> Looks great; thanks and welcome to Moto!

@spulec Thanks for merging my PR.I have been actively contributing to moto for quite some time now. :P

**Comment by spulec** [comment]
It says "First-time contributor" next to the PR?

**Comment by spulec** [comment]
Oh, I see now that you have contributed a bunch. I guess a bug with GitHub?

Screen Shot 2020-05-01 at 4 24 41 PM

Well then; thank you for your continued contributions! :)

**Pull request merged**
