### PR TITLE
Added DockerFile

### PR DESCRIPTION
**Pull request by ZuluPro**
Create DockerFile for use Moto's stand-alone server as a container. It uses Python 2 image.

With it:
```
docker build .
docker run <image_id>
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```

Maybe you want to register this image at DockerHub ?

### CODE REVIEW

**Comment by ZuluPro** [comment]
Any news ?

**Comment by kouk** [comment]
Do you maybe want to add some information to the README? like how to build and run?

**Comment by ZuluPro** [comment]
Yep,
Great idea, but will it be accepted?

Anthony Monthe

**Comment by kouk** [comment]
I would merge it, although I haven't been tracking the project lately and I'm not sure @spulec is OK with such initiatives :-)

**Comment by spulec** [comment]
Thanks!

**Pull request merged**
