### PR TITLE
fix(kms): allow describe key call by key arn

### PR DESCRIPTION
**Pull request by griffinb**
Resolves https://github.com/spulec/moto/issues/650.

### CODE REVIEW

**Comment by spulec** [comment]
Thanks for opening!

Looks like some tests need to be updated.

**Comment by griffinb** [comment]
Tests are passing now, but I don't know if they're passing for the right reason.  Is there a better way to change `models.py` to implement this feature?

**Comment by spulec** [comment]
Yeah, I think we are going to want to change describe_key to work with either and id or ARN passed through. Otherwise, it will appear as though there are twice as many keys as there really are.

**Comment by griffinb** [comment]
Hey @spulec would you mind taking a look at my latest changes?  Thanks!

**Comment by spulec** [comment]
Sorry for the delay. Can you get this so that it can merge cleanly to master?

**Comment by rocky4570** [comment]
Shouldnt this be resolved with #721 ?

Snippet of unit-test to describe via ARN.

+@mock_kms
 +def test_describe_key_via_arn():
 +    conn = boto.kms.connect_to_region("us-west-2")
 +    key = conn.create_key(policy="my policy", description="my key", key_usage='ENCRYPT_DECRYPT')
 +    arn = key['KeyMetadata']['Arn']
 +
 +    the_key = conn.describe_key(arn)
 +    the_key['KeyMetadata']['Description'].should.equal("my key")
 +    the_key['KeyMetadata']['KeyUsage'].should.equal("ENCRYPT_DECRYPT")
 +    the_key['KeyMetadata']['KeyId'].should.equal(key['KeyMetadata']['KeyId'])

**Comment by griffinb** [comment]
Yes, I believe https://github.com/spulec/moto/pull/721 took care of it.

**Comment by spulec** [comment]
Ah, cool. Going to close this then.

**Pull request closed without merging**
