### PR TITLE
Added support for WaitTimeSeconds in SQS #392

### PR DESCRIPTION
**Pull request by jotes**
Initial version of support for WaitTimeSeconds in sqs, @spulec  could you review?

### CODE REVIEW

**Comment by spulec** [comment]
It looks like there are a couple cloudformation tests that need updating too. If we can get those working, I'll be happy to merge!

**Comment by jotes** [comment]
@spulec sure thing! i'll do it later.

**Comment by jotes** [comment]
@spulec i fixed tests. Could you review again?

**Comment by spulec** [comment]
Thank you!

**Pull request merged**
