### PR TITLE
Fix:EC2-authorize_security_group_ingress- add description to IP-Ranges

### PR DESCRIPTION
**Pull request by usmangani1**
Fix:EC2-authorize_security_group_ingress- add description to IP-Ranges

https://github.com/localstack/localstack/issues/2775

### CODE REVIEW

**Comment by bblommers** [comment]
Looks like there are a few more failures now: https://travis-ci.org/github/spulec/moto/jobs/712835689

**Comment by usmangani1** [comment]
> Looks like there are a few more failures now: https://travis-ci.org/github/spulec/moto/jobs/712835689

@bblommers  where can I modify the response of this function.?There seem to be an extra key due to whcih it is failing.Can you please help me here? Thanks
sg.ip_permissions_egress
https://github.com/spulec/moto/blob/master/tests/test_ec2/test_security_groups.py#L856-L862

**Comment by bblommers** [comment]
Hi @usmangani1, the last issue was with CloudFormation - it would pass in the CidrIp as a string, so that needs some conversion as well: 
https://github.com/spulec/moto/pull/3196/files#diff-c397eb06557718aa69201d74d633b7dbR2092

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.15.dev1022

**Pull request merged**
