### PR TITLE
fix(org): close_account matches public API

### LINKED ISSUE #5063: Organizations close_account doesn't match public API
The Organizations close_account API was added in #5040.

It doesn't match the spec of the public [CloseAccount](https://docs.aws.amazon.com/organizations/latest/APIReference/API_CloseAccount.html) API.

> If the action is successful, the service sends back an HTTP 200 response with an empty HTTP body.

> While the close account request is in progress, Account status will indicate PENDING_CLOSURE. When the close account request completes, the status will change to SUSPENDED. 

The current implementation does neither of those things:

Here's the current implementation:

```python
class FakeAccount:
    ...
    @property
    def close_account_status(self):
        return {
            "CloseAccountStatus": {
                "Id": self.create_account_status_id,
                "AccountName": self.name,
                "State": "SUCCEEDED",
                "RequestedTimestamp": unix_time(datetime.datetime.utcnow()),
                "CompletedTimestamp": unix_time(datetime.datetime.utcnow()),
                "AccountId": self.id,
            }
        }

class OrganizationsBackend:
    ...
    def close_account(self, **kwargs):
        for account_index in range(len(self.accounts)):
            if kwargs["AccountId"] == self.accounts[account_index].id:
                closed_account_status = self.accounts[
                    account_index
                ].close_account_status
                del self.accounts[account_index]
                return closed_account_status

        raise AccountNotFoundException
```

The current implementation returns a CloseAccountStatus object. This does not exist in the public API. Indeed, the real CloseAccount API returns nothing.

The current implementation deletes the account from the backend's account list. That's wrong because the account should remain in the organization in a SUSPENDED state.

I caught this while adding type hints to the organizations models. There is no CloseAccountResponseTypeDef in mypy_boto3_organizations!

### PR DESCRIPTION
**Pull request by iainelder**
* Returns no response body
* Account remains in org in SUSPENDED state

Fixes #5063.

### CODE REVIEW

**Comment by iainelder** [comment]
Not sure why the Terraform test failed!

```
=== CONT  TestAccELBAttachment_basic
    attachment_test.go:19: Step 3/4 error: Check failed: Check 2/2 error: instance count does not match: expected 2, got 1
```

I didn't change anything in Terraform or in ELB.

**Comment by bblommers** [comment]
> Not sure why the Terraform test failed!
> 

I've restarted the tests, and it passes now. :+1:

**Comment by bblommers** [comment]
@donelupus As the original submitted of this feature - do you see any issues with this change?

**Review by bblommers — APPROVED** [review]
LGTM - I've tested this a bit, and AWS seems to behave the same way

**Comment by iainelder** [comment]
Thanks @bblommers . Feel free to invite my review on new PRs for moto's Organizations APIs. I plan to depend on moto for testing my apps that work with Organizations APIs so I would like check the changes.

I don't think Github allows me to watch just part of the repo. I don't want to watch all changes because this is a busy project!

**Comment by bblommers** [comment]
I'll keep that in mind @iainelder, appreciate the offer. I'll mention you if anything happens in this API. :slightly_smiling_face:

**Pull request merged**
