### PR TITLE
IAM:detach_*_policy(): Fix divergent error handling with aws

### PR DESCRIPTION
**Pull request by wonhyeongseo**
fix https://github.com/localstack/localstack/issues/6989
referred here by https://github.com/localstack/moto/pull/58

Existing un-attached user policy throwed a 500 InternalError unexpectedly, whilst non-existing user policy throwed 404 IAMNotFoundException as expected.
image

This can be solved by checking if the user is linked with the policy-arn given.
image

Other things to consider include:
- This problem seems to apply to other `detach_*_policy` implementations inside code, such as group and role. _Should we open another issue to resolve these?_
- May you please add the `hacktoberfest-accepted` tag to this PR if possible? Thank you.

### CODE REVIEW

**Review by bblommers — CHANGES_REQUESTED** [review]
Would you mind adding a test for this @wonhyeongseo, to verify that this behaves as it should?
See our docs on some guidance on how to write negative tests: http://docs.getmoto.org/en/latest/docs/contributing/development_tips/tests.html

**Comment by bblommers** [comment]
> 
>     * This problem seems to apply to other `detach_*_policy` implementations inside code, such as group and role. _Should we open another issue to resolve these?_
> 

Yes please! The closer we can get to mimick AWS' behaviour, the better.

**Comment by wonhyeongseo** [comment]
Hello @bblommers, how are you?
Sorry for the long wait, may you please review my first go at writing pytest? A thorough criticism will be very welcomed. 
image

Thank you. Have a great week ahead :)

**Review by bblommers — APPROVED** [review]
LGTM - thank you again for raising and fixing this @wonhyeongseo!

**Pull request merged**
