### PR TITLE
Fix/asg attach instances

### PR DESCRIPTION
**Pull request by mello7tre**
fix to #2123 (attach_instances)
    
    In attach_instances add autoscaling_group property to attached instances
    as an InstanceState property

### CODE REVIEW

**Review by bblommers — CHANGES_REQUESTED** [review]
Hi @mello7tre, thanks for the PR!
Would you mind adding the testcase from the original issue here, to showcase that this works?

**Comment by mello7tre** [comment]
> Hi @mello7tre, thanks for the PR!
> Would you mind adding the testcase from the original issue here, to showcase that this works?

do you mean create a test under `tests/test_autoscaling` that create the server and then a client that execute the calls ?

**Comment by bblommers** [comment]
In `tests/test_autoscaling/test_autoscaling.py`, yeah - you don't have to create the server though, just take the decorated test that was posted in the [first comment](https://github.com/spulec/moto/issues/2123#issuecomment-475355108).

**Review by bblommers — APPROVED** [review]
Nice one - thanks again @mello7tre!

**Pull request merged**
