### PR TITLE
fix lambda endpoint parsing

### PR DESCRIPTION
**Pull request by thehesiod**
fixes https://github.com/spulec/moto/issues/1394 and SNS lambda invoke due to https://github.com/spulec/moto/commit/d5ee48eedd0c9324ba6510f66634d31626bef68b#diff-2df06bdd95e3c78b9335da9f260a3472

### CODE REVIEW

**Comment by terrycain** [comment]
Do we have any tests supporting the changes in models.py?

**Comment by thehesiod** [comment]
I'll add one after getting back from our conference

**Comment by JackDanger** [comment]
This is blocked pending tests but otherwise ready to merge!

**Comment by thehesiod** [comment]
totally forgot about this pr

**Comment by thehesiod** [comment]
ok, that should do it!

**Comment by JackDanger** [comment]
nice work, @thehesiod!!

**Pull request merged**
