### PR TITLE
events: fix archive event pattern match check

### PR DESCRIPTION
**Pull request by elopez**
There is a missing `return True` for the positive match case in
matches_pattern, causing all valid patterns to fail.

### CODE REVIEW

**Review by bblommers — CHANGES_REQUESTED** [review]
Hi @elopez, thanks for the PR! Would you mind adding a unit test for this, to verify this now works correctly?

**Comment by elopez** [comment]
Hi! I'll try to get some time to write the test soon, but if anyone else wants to do it meanwhile, feel free 👍

**Comment by elopez** [comment]
Hi @bblommers, I updated one of the existing tests to check this case as well. The current test only considered the empty pattern and the "non-empty but not matching" pattern cases, so I added an instance of the "non-empty and matching" case.

**Review by bblommers — APPROVED** [review]
LGTM - thanks @elopez!

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.17.dev270

**Pull request merged**
