### PR TITLE
Fixing UnboundLocalError

### PR DESCRIPTION
**Pull request by bay-street-garreth**
UnboundLocalError is thrown when creating a Firehose delivery stream.

Error:
moto/kinesis/responses.py:198: UnboundLocalError

Sample Code:
```
    firehose_client = boto3.client("firehose", region_name=REGION)
    firehose_client.create_delivery_stream(DeliveryStreamName=OUTPUT_STREAM_NAME)
```

### CODE REVIEW

**Review by bblommers — CHANGES_REQUESTED** [review]
Hi @bay-street-garreth, thanks for the PR!
Would you mind adding a unit test for this, to ensure that at least it doesn't throw an error anymore?

**Comment by bblommers** [comment]
Related to #3862

**Comment by bay-street-garreth** [comment]
@bblommers .. I took a look at the ticket you mentioned above and added ElasticsearchDestinationConfiguration support with some tests. Let me know if there's anything else I need to add to the PR.

**Review by bblommers — APPROVED** [review]
LGTM! Thanks again @bay-street-garreth

**Pull request merged**
