### PR TITLE
Validate message group ID for standard queues

### LINKED ISSUE #4594: sqs: successfull send_message with MessageGroupID on standard queues
According to AWS documentation MessageGroupId is not required for standard queues and if you send it fails with message: 

`botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the SendMessage operation: Value default for parameter MessageGroupId is invalid. Reason: The request include parameter that is not valid for this queue type.`

That doesn't happen when MessageGroupId is sent on a standard queue with moto:

```python

sqs = boto3.client('sqs', region_name=Region)
queue = sqs.create_queue(
    QueueName='input_test_queue',
    Attributes={
        'VisibilityTimeout': '5'
    }
)

queue_url  = queue["QueueUrl"]
sqs.send_message(
            QueueUrl=queue_url,
            MessageBody=json.dumps({}),
            MessageGroupId="MessageGroup"
        )

```

Code above should fail but works successfully.

moto version == 2.0.11

### PR DESCRIPTION
**Pull request by kamilturek**
This PR introduces the validation to prevent sending a message group ID when using a queue of standard type.

Closes #4594.

### CODE REVIEW

**Review by bblommers — CHANGES_REQUESTED** [review]
Hi @kamilturek, thanks for the PR! Happy to merge this once the build passes

**Comment by kamilturek** [comment]
Hi, @bblommers. Thanks, that should be fixed now.

**Comment by kamilturek** [comment]
Yeah, I think this is the moment 😄

**Review by bblommers — APPROVED** [review]
LGTM! Thanks @kamilturek

**Pull request merged**
