### PR TITLE
Fixed #1261 dynamodb FilterExpression bugs

### LINKED ISSUE #1261: moto 1.1.22 breaks dynamodb scan
Hello, I have an issue that started with moto 1.1.22. Reproduce with:

test_moto_failure.py
```from moto import mock_dynamodb2
import boto3

@mock_dynamodb2
def test_moto_problem():

    client = boto3.client('dynamodb',
                          aws_access_key_id="FakeKey",
                          aws_secret_access_key='FakeSecretKey',
                          aws_session_token='FakeSessionToken')

    table = client.create_table(
        TableName='table_name',
        KeySchema=[
            {
                'AttributeName': 'id',
                'KeyType': 'HASH'
            }
        ],
        AttributeDefinitions=[
            {
                'AttributeName': 'time-bucket',
                'AttributeType': 'N'
            }
        ],
        ProvisionedThroughput={
            'ReadCapacityUnits': 5,
            'WriteCapacityUnits': 5
        }
    )

    resp = client.scan(TableName='table_name',
                       Select='ALL_ATTRIBUTES',
                       FilterExpression='#tb >= :dt',
                       ExpressionAttributeNames={"#tb": "time-bucket"},
                       ExpressionAttributeValues={":dt": {"N": str(100)}
                                                  }
                       )
```

Environment:

```
$ pip freeze
asn1crypto==0.23.0
awscli==1.11.170
boto==2.48.0
boto3==1.4.7
botocore==1.7.28
certifi==2017.7.27.1
cffi==1.11.2
chardet==3.0.4
colorama==0.3.7
cookies==2.2.1
cryptography==2.1.1
daiquiri==1.3.0
dicttoxml==1.7.4
docker==2.5.1
docker-pycreds==0.2.1
docutils==0.14
idna==2.6
Jinja2==2.9.6
jmespath==0.9.3
MarkupSafe==1.0
mock==2.0.0
moto==1.1.22
numpy==1.13.1
pandas==0.20.3
pbr==3.1.1
py==1.4.34
pyaml==17.10.0
pyasn1==0.3.7
pycparser==2.18
pytest==3.2.1
python-dateutil==2.6.1
pytz==2017.2
PyYAML==3.12
requests==2.18.4
rsa==3.4.2
s3transfer==0.1.11
scikit-learn==0.19.0
scipy==0.19.1
six==1.10.0
urllib3==1.22
websocket-client==0.44.0
Werkzeug==0.12.2
xmltodict==0.11.0
```

`$ python -m pytest -k "test_moto_problem"`

Error:

```
======================================================================================================= test session starts =======================================================================================================
platform darwin -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /Users/william/Documents/bde-deckard/score_server, inifile:
collected 9 items                                                                                                                                                                                                                  

tests/test_moto_failure.py F

============================================================================================================ FAILURES =============================================================================================================
________________________________________________________________________________________________________ test_moto_problem ________________________________________________________________________________________________________

    @mock_dynamodb2
    def test_moto_problem():
    
        client = boto3.client('dynamodb',
                              aws_access_key_id="FakeKey",
                              aws_secret_access_key='FakeSecretKey',
                              aws_session_token='FakeSessionToken')
    
        table = client.create_table(
            TableName='table_name',
            KeySchema=[
                {
                    'AttributeName': 'id',
                    'KeyType': 'HASH'
                }
            ],
            AttributeDefinitions=[
                {
                    'AttributeName': 'time-bucket',
                    'AttributeType': 'N'
                }
            ],
            ProvisionedThroughput={
                'ReadCapacityUnits': 5,
                'WriteCapacityUnits': 5
            }
        )
        epoch = "1000"
    
        resp = client.scan(TableName='table_name',
                           Select='ALL_ATTRIBUTES',
                           FilterExpression='#tb >= :dt',
                           ExpressionAttributeNames={"#tb": "time-bucket"},
>                          ExpressionAttributeValues={":dt": {"N": str(100)}
                                                      }
                           )

tests/test_moto_failure.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../anaconda/envs/deckard/lib/python3.6/site-packages/botocore/client.py:312: in _api_call
    return self._make_api_call(operation_name, kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <botocore.client.DynamoDB object at 0x107b044a8>, operation_name = 'Scan'
api_params = {'ExpressionAttributeNames': {'#tb': 'time-bucket'}, 'ExpressionAttributeValues': {':dt': {'N': '100'}}, 'FilterExpression': '#tb >= :dt', 'Select': 'ALL_ATTRIBUTES', ...}

    def _make_api_call(self, operation_name, api_params):
        operation_model = self._service_model.operation_model(operation_name)
        request_context = {
            'client_region': self.meta.region_name,
            'client_config': self.meta.config,
            'has_streaming_input': operation_model.has_streaming_input,
            'auth_type': operation_model.auth_type,
        }
        request_dict = self._convert_to_request_dict(
            api_params, operation_model, context=request_context)
    
        handler, event_response = self.meta.events.emit_until_response(
            'before-call.{endpoint_prefix}.{operation_name}'.format(
                endpoint_prefix=self._service_model.endpoint_prefix,
                operation_name=operation_name),
            model=operation_model, params=request_dict,
            request_signer=self._request_signer, context=request_context)
    
        if event_response is not None:
            http, parsed_response = event_response
        else:
            http, parsed_response = self._endpoint.make_request(
                operation_model, request_dict)
    
        self.meta.events.emit(
            'after-call.{endpoint_prefix}.{operation_name}'.format(
                endpoint_prefix=self._service_model.endpoint_prefix,
                operation_name=operation_name),
            http_response=http, parsed=parsed_response,
            model=operation_model, context=request_context
        )
    
        if http.status_code >= 300:
            error_code = parsed_response.get("Error", {}).get("Code")
            error_class = self.exceptions.from_code(error_code)
>           raise error_class(parsed_response, operation_name)
E           botocore.exceptions.ClientError: An error occurred (InternalFailure) when calling the Scan operation: Internal error. replace() argument 2 must be str, not float

../../../anaconda/envs/deckard/lib/python3.6/site-packages/botocore/client.py:601: ClientError
```

The error `replace() argument 2 must be str, not float` is very odd because clearly I'm sending `str(100)` as my `ExpressionAttributeValues`.

When using `pip install moto==1.1.21` the test passes.

### PR DESCRIPTION
**Pull request by terrycain**
FilterExpression was incorrectly handling numbers, stupid typo there. 
Also `>=` `<=` and `<>` was not being parsed correctly.

Should be good now.

### CODE REVIEW

**Comment by terrycain** [comment]
Hold off on this probs can fix #1263 here too

**Comment by terrycain** [comment]
Ok, I think that'll do it. Though I'm sure the community will find more bugs now that FilterExpressions are no longer ignored :wink:, but if they do I'll fix them when they come up

**Comment by JackDanger** [comment]
Great work, @terrycain !

**Comment by JackDanger** [comment]
This is released as Moto 1.1.23

**Comment by batkuip** [comment]
Don't think this is 100% yet.  Seems be some issues with AND / OR.  For example: `Attr('epoch_ts').lt(cutoff) & Attr('fanout_ts').not_exists()`  results in  `Bad Filter Expression: Malformed filter expression`

**Comment by terrycain** [comment]
@batkuip Yeah there's going to be some issues with it, raise an issue with that expression and I'll look into it

**Pull request merged**
