### PR TITLE
NoSuchKey error in S3 is actually '404'

### LINKED ISSUE #571: S3 not found error differs from AWS response
When trying to access a key that is not present, moto returns this:

```python
{
    'ResponseMetadata': {
        'HTTPStatusCode': 404, 'HostId': '', 'RequestId': ''
    },
    'Error': {
        'Message': 'Not Found',
        'Code': '404'
    }
}
```
vs AWS S3 returning this:

```python
{
    'ResponseMetadata': {
        'HTTPStatusCode': 404, 'HostId': 'my-host-id', 'RequestId': 'some-request-id'
    },
    'Error': {
        'Message': 'The specified key does not exist.',
        'Code': 'NoSuchKey',
        'Key': 'my-s3-prefix/object-id'
    }
}
```
`Error.Code` is were the important difference lies. Handling of '404' vs 'NoSuchKey' will be very different. moto's '404'  also doesn't let you differentiate between bucket not found and key not found.

### PR DESCRIPTION
**Pull request by JackDanger**
Fixes #571 and #953

### CODE REVIEW

**Comment by JackDanger** [comment]
@georgepsarakis Would you mind taking a look at this? It appears AWS does not, despite the docs, return a 'NoSuchKey' error code, it returns '404'. I reproduced this but would love if you could try it as well in case you see something I missed.

**Comment by georgepsarakis** [comment]
As you mentioned above the documentation says that the HTTP status code is 404, but the 
`<Code>` field contains the value `NoSuchKey`. Have you tried it with AWS directly and it does not return this response?

**Comment by JackDanger** [comment]
> Have you tried it with AWS directly and it does not return this response?

Yes, and that's the most confusing part about this. Here's a recreation:

```
try:
  boto3.session.Session(region_name='us-west-1').resource('s3').Object('real-bucket', key='does-not-exist').load()
except Exception as e:
  pass
print(e.response)
{'Error': {'Code': '404', 'Message': 'Not Found'},
 'ResponseMetadata': {'HTTPHeaders': {'content-type': 'application/xml',
   'date': 'Wed, 17 May 2017 19:55:45 GMT',
   'server': 'AmazonS3',
   'transfer-encoding': 'chunked',
   'x-amz-id-2': 'CqX9MueZUQpD1oQGSxUrRRXpleR4o0oa3SKE6WPDMry/IKecB5m2FOAcNMbUPxT8j1DpVwbY9tU=',
   'x-amz-request-id': 'AC981B0B8540A48E'},
  'HTTPStatusCode': 404,
  'HostId': 'CqX9MueZUQpD1oQGSxUrRRXpleR4o0oa3SKE6WPDMry/IKecB5m2FOAcNMbUPxT8j1DpVwbY9tU=',
  'RequestId': 'AC981B0B8540A48E',
  'RetryAttempts': 1}}
```

**Comment by peterbe** [comment]
I'm running `boto3==1.4.4` and `botocore==1.5.48`. 

The tricky thing is that the Code is different depending on if you do a `get_object` or `head_object`.

Consider the following...
```python
from botocore.exceptions import ClientError
import boto3
s3_client = boto3.client('s3')
try:
    s3_client.get_object(Bucket='real-bucket', Key='doesnotexist')
except ClientError as exc:
    print(exc.response['Error']['Code'])

try:
    s3_client.head_object(Bucket='real-bucket', Key='doesnotexist')
except ClientError as exc:
    print(exc.response['Error']['Code'])
```

The output is...:
```
NoSuchKey
404
```
`moto` just needs to do the same. I think it did prior to 1.0.0.

**Comment by JackDanger** [comment]
@peterbe I've changed it such that HEAD requests and GET requests return different error codes. This appears to be how it worked before May 1st when the exceptions were refactored. The tests have been updated to prevent a regression.

**Pull request merged**
