### PR TITLE
Fix issue #4906 by removing version stages from old versions

### PR DESCRIPTION
**Pull request by stromp**

### CODE REVIEW

**Review by bblommers — CHANGES_REQUESTED** [review]
Hi @stromp, thanks for the PR! You might have to merge in the latest master to get the build to pass, I've just (30 mins ago) pushed a change with a fix for the failing tests

**Comment by stromp** [comment]
@bblommers all checks are now okay, can you merge the PR? Another question, when is the next release plannend?

**Review by bblommers — APPROVED** [review]
LGTM - thanks for the fix!

**Comment by bblommers** [comment]
> Another question, when is the next release plannend?

No promises - but I'll try to cut a release this weekend

**Comment by bblommers** [comment]
@stromp Moto 3.0.6 has just been released

**Comment by stromp** [comment]
Thanks! Will start using it next monday!

**Pull request merged**
