### PR TITLE
Bugfix #1874 - Limit DynamoDB item size to 400KB

### PR DESCRIPTION
**Pull request by bblommers**

### CODE REVIEW

**Comment by bblommers** [comment]
Fixes https://github.com/spulec/moto/issues/1874

**Comment by bblommers** [comment]
Tests are failing - will have a look later on

**Comment by spulec** [comment]
This looks great; thanks! Can you add a couple more test for the other object type sizes?

**Comment by bblommers** [comment]
Added some more tests @spulec  - let me know if you want to see some more usecases

**Comment by spulec** [comment]
Looks great; thanks!

**Pull request merged**
