### PR TITLE
Replace email with username in cogntio JWT tokens

### PR DESCRIPTION
**Pull request by mglowinski93**
According to [documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-the-access-token.html) JWT token must contain "username" and not `email`. In edge case, `username` can contain `sub` as value, but implementation of this package does not support that situation, so simply `email` was replaced with `username`.

### CODE REVIEW

**Review by bblommers — CHANGES_REQUESTED** [review]
Hi @mglowinski93, thanks for the PR!

We already have a test case (`tests/test_congitoidp/test_cognitoidp.py::test_token_legitimacy`) where we verify that the jwt-token is correct - can you add an assertion there that the `username`-field is set, and contains the correct value?

**Comment by mglowinski93** [comment]
> Hi @mglowinski93, thanks for the PR!
> 
> We already have a test case (`tests/test_congitoidp/test_cognitoidp.py::test_token_legitimacy`) where we verify that the jwt-token is correct - can you add an assertion there that the `username`-field is set, and contains the correct value?

Done.

**Review by bblommers — APPROVED** [review]
Awesome - thanks again @mglowinski93!

**Comment by mglowinski93** [comment]
> Awesome - thanks again @mglowinski93!

Glad to help :)

**Pull request merged**
