### PR TITLE
Add extra keys to EC2 `describe-addresses` operation

### LINKED ISSUE #4088: Add PrivateIpAddress field for Elastic Ip Model
When associating mocked elastic ips to a mocked resource (ec2, rds, etc), the elastic ip model should include a PrivateIpAddress field which would be shown in a response from the ec2 client `describe_addresses` method as in the example in the boto3 docs here https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.describe_addresses

Version:
moto==2.0.4

### PR DESCRIPTION
**Pull request by gmcrocetti**
### Description

Added two new keys for the `describe-addresses` response:
1. `PrivateIPAddress`; 
2. `NetworkInterfaceOwnerId`.

Updated comment with outdated cloudformation link.

closes #4088.

### CODE REVIEW

**Comment by bblommers** [comment]
@gmcrocetti The failing test is probably just flaky, but it would be good to get some confirmation on that. Would you mind merging in the latest master? Fingers crossed that will fix it

**Comment by gmcrocetti** [comment]
It failed again :crying_cat_face: . But due to a completely unrelated reason (SQS) ...

**Comment by bblommers** [comment]
This does look related:
```
FAILED tests/test_ec2/test_elastic_ip_addresses.py::test_describe_addresses_with_vpc_associated_eni
```
```
>       result["Addresses"].should.have.length_of(1)

tests/test_ec2/test_elastic_ip_addresses.py:695: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <sure.AssertionBuilder object at 0x7fe9c301d850>, args = (1,), kw = {}

    @wraps(func)
    def wrapper(self, *args, **kw):
        try:
            value = func(self, *args, **kw)
        except AssertionError as e:
>           raise AssertionError(e)
E           AssertionError: the length of [{'InstanceId': '', 'PublicIp': '127.198.126.248', 'Domain': 'standard', 'NetworkInterfaceId': '', 'Tags': []}, {'InstanceId': '', 'PublicIp': '127.34.65.154', 'AllocationId': 'eipalloc-56ce6f03', 'AssociationId': 'eipassoc-59bd07b3', 'Domain': 'vpc', 'NetworkInterfaceId': 'eni-a9726ff9', 'NetworkInterfaceOwnerId': '123456789012', 'PrivateIpAddress': '10.0.58.252', 'Tags': []}] should be 1, but is 2
```
Maybe there's something wrong with the resulting XML format, that boto3 thinks there are two addresses?

**Comment by gmcrocetti** [comment]
I couldn't reproduce it locally (Just ran the `tests_ec2` module). Looks like there's a test or fixture creating an extra address. I'm filtering by the allocation-id now, therefore, should be only one.

**Review by bblommers — APPROVED** [review]
Looks like that fixed it. Thanks @gmcrocetti!

**Comment by gmcrocetti** [comment]
> Looks like that fixed it. Thanks @gmcrocetti!

Thanks a lot for the help o/

**Pull request merged**
