### PR TITLE
Some more CloudFormation functionality

### PR DESCRIPTION
**Pull request by 2rs2ts**
* Implements updating for:
    * ASGs
    * Launch Configurations
    * ELBs
    * Route53 records
* Adds support for:
    * ELB health checks
    * `GetAtt` (for `DNSName` in ELBs only, since it was the only thing I needed when working on my own code.)
    * `UsePreviousTemplate` in `Stack.update`
* Fixes:
    * Sets stack status to `UPDATE_COMPLETE` after updating the stack

### CODE REVIEW

**Comment by 2rs2ts** [comment]
I'll work on adding a few more tests to appease coveralls.

**Comment by 2rs2ts** [comment]
Closing until I get a chance to work on this again.

**Comment by 2rs2ts** [comment]
Can someone take a look at this now?

**Comment by spulec** [comment]
I'm having an issue with one of the tests now (`tests/test_cloudformation/test_cloudformation_stack_crud_boto3.py:test_describe_deleted_stack`). It seems to be trying to call `Instance.delete`, but our Instance class doesn't have a `delete` method.

```
  File "/Users/spulec/Development/moto/moto/core/responses.py", line 95, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/Users/spulec/Development/moto/moto/core/responses.py", line 138, in _dispatch
    return self.call_action()
  File "/Users/spulec/Development/moto/moto/core/responses.py", line 154, in call_action
    response = method()
  File "/Users/spulec/Development/moto/moto/cloudformation/responses.py", line 152, in delete_stack
    self.cloudformation_backend.delete_stack(name_or_stack_id)
  File "/Users/spulec/Development/moto/moto/cloudformation/models.py", line 120, in delete_stack
    stack.delete()
  File "/Users/spulec/Development/moto/moto/cloudformation/models.py", line 57, in delete
    self.resource_map.delete()
  File "/Users/spulec/Development/moto/moto/cloudformation/parsing.py", line 414, in delete
    raise last_exception
AttributeError: 'Instance' object has no attribute 'delete'
```

**Comment by spulec** [comment]
Got it fixed, thanks for your work!

**Comment by 2rs2ts** [comment]
Ah, sorry that I didn't see your issue earlier, but I'm glad you got it fixed. :+1:

**Pull request closed without merging**
