### PR TITLE
Directory Service, Route53Resolver:  Delete network interfaces created during initialization

### PR DESCRIPTION
**Pull request by kbalk**
Directory Service creates a security group and network interfaces, but those weren't being deleted when a directory was deleted.  Also, the Security Group Id should be displayed in the `describe_directory` output.

Route53Resolver creates network interfaces for the endpoint and those should be deleted when the endpoint is deleted.

### CODE REVIEW

**Review by bblommers — CHANGES_REQUESTED** [review]
Hey @kbalk, would you mind adding some assertions to the existing deletion-tests to verify that the ENI's/SG's have been deleted?

**Comment by kbalk** [comment]
> Hey @kbalk, would you mind adding some assertions to the existing deletion-tests to verify that the ENI's/SG's have been deleted?

I knew you were going to make that suggestion, but got lazy!

**Comment by kbalk** [comment]
@bblommers Made the additions ...

**Review by bblommers — APPROVED** [review]
Thanks @kbalk

**Pull request merged**
