### PR TITLE
Fixed AWS Config S3 ACL issues

### LINKED ISSUE #3986: AWS Config S3 ACLs missing owner
It looks like AWS Config for S3 has a slightly different behavior from when I initially wrote the capability a while back. AWS Config is now including the default account owner ACL in the grantees now.

The following lines need to be removed:
https://github.com/spulec/moto/blob/master/moto/s3/models.py#L439-L441

I will make a PR soon to fix.

### PR DESCRIPTION
**Pull request by mikegrima**
- AWS Config appears to have changed how ACLs are returned
- This PR makes moto's behavior consistent with AWS Config's S3 representation

Fixes #3986

### CODE REVIEW

**Review by bblommers — APPROVED** [review]
LGTM. Thanks for the fix @mikegrima!

**Comment by mikegrima** [comment]
@bblommers You have a few PRs that are open. Are they ready for merging?

**Comment by bblommers** [comment]
> @bblommers You have a few PRs that are open. Are they ready for merging?

They should be! Just waiting for a review/approval

**Comment by mikegrima** [comment]
I'll try to take a look later, but totally feel free to merge them in if you feel confident in them.

**Pull request merged**
