### PR TITLE
Feature S3 Object Lock

### PR DESCRIPTION
**Pull request by pinzon**
While trying to solve issue localstack/localstack#4166 I figure out that moto doesnt have the [Object Lock feature](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock-overview.html) of the S3 service.

So I implemented it, including some validations necessary to solve the issue previously mentioned.  

The quirk of this implementation is that the retention lock is that only forces the lock when is set to COMPLIANCE mode.

### CODE REVIEW

**Comment by bblommers** [comment]
Hi @pinzon, thanks for the PR!
Would you mind running the linter on this? The CI currently fails on the formatting.
```
pip install black==19.10b0
make format
make lint
```

**Comment by pinzon** [comment]
@bblommers thanks for the commands, I was running format with the wrong black version.
Just pushed a new commit.

**Comment by pinzon** [comment]
@bblommers I'm not sure what to do to make the tests pass in server mode. 
To me it seems that the headers related to object lock are not being detected at the moto server.

**Comment by pinzon** [comment]
The last commit changes the usage of `headers` to `self.headers` because the s3-object lock params weren't being detected.
Thank you @bblommers for your help.

**Review by bblommers — APPROVED** [review]
LGTM - thank you @pinzon!

**Pull request merged**
