### PR TITLE
feat(events): Add policy in put_permission

### PR DESCRIPTION
**Pull request by GonzaloSaad**
Work Done
---
Create EventBus permission from `policy`. Also add `RemoveAllPermissions` in `remove_permission`

Tests
---
- [x] `TestAccAWSCloudwatchEventBusPolicy_basic`
- [x] `TestAccAWSCloudwatchEventBusPolicy_disappears`

image

Also passed in moto terraform tests with motoserver: 
image

Test [suite](https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_cloudwatch_event_bus_policy_test.go) completed :partying_face: 

Existing behaviour for permissions is working too! 
```python3
import boto3
session = boto3.Session(aws_access_key_id="root", aws_secret_access_key="root", region_name="us-east-1")
events_client = session.client("events", endpoint_url="http://localhost:4566")

try:
    events_client.create_event_bus(Name="GonzaloTest")
    _ = events_client.put_permission(
        EventBusName="GonzaloTest",
        Action="events:PutEvents",
        StatementId="MyTest",
        Principal="598320245376",
    )
    describe_response = events_client.describe_event_bus(Name="GonzaloTest")
    print(describe_response)
```

<details>
<summary>Response </summary>
<p>

```json
{
  "Name": "GonzaloTest",
  "Arn": "arn:aws:events:us-east-1:000000000000:event-bus/GonzaloTest3",
  "Policy": "{\"Version\": \"2012-10-17\", \"Statement\": [{\"Sid\": \"MyTest\", \"Effect\": \"Allow\", \"Principal\": {\"AWS\": \"arn:aws:iam::598320245376:root\"}, \"Action\": \"events:PutEvents\", \"Resource\": \"arn:aws:events:us-east-1:000000000000:event-bus/GonzaloTest\"}]}",
  "ResponseMetadata": {
    "HTTPStatusCode": 200,
    "HTTPHeaders": {
      "content-type": "text/html; charset=utf-8",
      "content-length": "377",
      "access-control-allow-origin": "*",
      "access-control-allow-methods": "HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH",
      "access-control-allow-headers": "authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging,amz-sdk-invocation-id,amz-sdk-request",
      "access-control-expose-headers": "x-amz-version-id",
      "connection": "close",
      "date": "Sat, 31 Jul 2021 01:37:24 GMT",
      "server": "hypercorn-h11"
    },
    "RetryAttempts": 0
  }
}
```
</p>
</details>  

<details>
<summary>Policy </summary>
<p>

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "MyTest",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::598320245376:root"
      },
      "Action": "events:PutEvents",
      "Resource": "arn:aws:events:us-east-1:000000000000:event-bus/GonzaloTest"
    }
  ]
}
```
</p>
</details>

### CODE REVIEW

**Comment by GonzaloSaad** [comment]
I see this error in the terraform step! 
image

What should I do here? :partying_face: :parrot:

**Comment by bblommers** [comment]
Looks like it is the new test that's still failing on our CI:
`{'name': 'TestAccAWSCloudwatchEventBusPolicy', 'time': 0.0, 'errors': 2.0, 'failures': 0.0, 'skipped': 0.0, 'tests': 2.0, 'passed': 0.0}`

Are you running the test locally against Localstack, or against a newly build MotoServer?

**Comment by GonzaloSaad** [comment]
@bblommers, ok that is the test my PR should add :joy: 

I'm running against `localstack`. I do the following:

1. Change stuff in a local `moto` branch. 
2. `pip install` the local lib in `localstack`. 
3. Start `localstack` 
4. Run the tests

Maybe I'm missing something!

**Comment by GonzaloSaad** [comment]
Alright, I saw the motoserver getting started on the tests in CI! 

I'll do that and see what's going on! Feel free to close the PR if its adding noise!

**Review by bblommers — APPROVED** [review]
LGTM - thanks for the fix @GonzaloSaad!

**Comment by GonzaloSaad** [comment]
> LGTM - thanks for the fix @GonzaloSaad!

Thank you and sorry for the delay in the fix! Have a good day!

**Pull request merged**
