### PR TITLE
Add support for copying EBS snapshots

### PR DESCRIPTION
**Pull request by philchristensen**
I haven't yet created unit tests for this, but it was an essential addition I needed for my testing. If I have the time I'll submit tests ASAP.

### CODE REVIEW

**Comment by JackDanger** [comment]
@philchristensen This is awesome and folks using Moto would really appreciate it. Do you mind just taking a quick attempt at the tests and then if you get blocked passing it off to any other contributor?
The place to start is in `tests/test_ec2/test_elastic_block_store.py`

**Comment by philchristensen** [comment]
Thanks! I definitely intend to try to write those tests, I'm using moto a lot. I don't have a specific timeline, but I'll do my best!

**Comment by philchristensen** [comment]
Okay, I've added the unit test and it seems pretty good. It's based on the copy_ami test, but written in boto3.

**Comment by spulec** [comment]
Looks great; thanks!

**Pull request merged**
