### PR TITLE
Added more output to scaffold.py

### PR DESCRIPTION
**Pull request by terrycain**
Just added line at the bottom that reminds others what files also need to be modified, pretty sure I got everything.

### CODE REVIEW

**Comment by toshitanian** [comment]
@terrycain 
is adding `urls.py` and  adding the backend into "backends.py is necessary with every services?
if it is the case, i'll fix the scaffold script.

**Comment by terrycain** [comment]
@toshitanian I think so, but with some effort we could probably remove most urls.py if we can programatically define the url routes in the Response object/s, and going on from that could probably autodiscover each API. But for now it would be useful I think.

**Comment by toshitanian** [comment]
@terrycain I think I can find the url from botocore. will make a another PR.
You can merge this PR :)

**Comment by JackDanger** [comment]
This is released as Moto version 1.1.15

**Pull request merged**
