### PR TITLE
Replace and delete Network ACL Entries

### PR DESCRIPTION
**Pull request by JeromeBosman**
Hello,

Please find an implementation for ec2.delete_network_acl_entry and ec2.replace_network_acl_entry.

With tests.

Hope this helps.

Note: could you please give me some quick steps to build/run on Windows? Thanks.

### CODE REVIEW

**Comment by spulec** [comment]
Looks great, thanks for your help!

**Comment by JeromeBosman** [comment]
np, would do more if I knew how to:

   - build the lib locally so I can deploy my fork
   - run the tests locally, so I don't use Travis to check my code is
   working (which I did this afternoon)

I'm on Windows.

Jerome

**Comment by spulec** [comment]
What happens after you git clone and run `make init`?

**Comment by JeromeBosman** [comment]
last lines of make init:

Installing collected packages: cookies, dicttoxml, pyaml, moto
  Found existing installation: moto 0.4.31
    Uninstalling moto-0.4.31:
      Successfully uninstalled moto-0.4.31
  Running setup.py develop for moto
Successfully installed cookies-2.2.1 dicttoxml-1.7.4 moto pyaml-16.12.2

**Comment by JeromeBosman** [comment]
ok, building & tests running locally

thanks for the hint

J

**Pull request merged**
