### PR TITLE
S3 cloudformation update

### PR DESCRIPTION
**Pull request by jweite**
Re Issue #3187

Mere's a first cut for early review and discussion.  It utilizes the abstract base class technique @bblommers  prototyped in PR3185 to move CloudFormation resource type and name attribute to the model object.  I had anticipated needing that functionality to allow the cloudformation module to determine the type of an update from a cloudformation_update_type() method in the model object and exclude the forcing of name params into the update json, but subsequent guidance from @bblommers pointed toward a technique where the name param is only forced into the cloudformation_json for creates and deletes.  So the abstract base class isn't strictly needed here after all, but since it's a valuable step toward cloudformation support decentralization, I'm happy to leave it in unless there are objections.

Key thing to point out are that the S3 FakeS3Bucket now have create, uddate and delete_from_cloudformation_json methods.  The update_from_cloudformation_json method determines whether the update is a replacement update, and if so, creates a new bucket and deletes the old.  Otherwise it updates-in-place.

Unit tests of in-place update (encryption) and replacement update (name) are present.  Still TBD is a test to confirm that a replacement update using the same name fails.

So far I only support the Encryption properties.  Property support will get a little verbose, so I wanted to do initial review before getting into that.

### CODE REVIEW

**Comment by jweite** [comment]
Another consult @bblommers.  As you see some transformation of the cloudformation json into AWS API terms was necessary, and expect that similar will be required for the other properties.  I elected to do that in straight python in funcs in the newly added s3 cloud_formation.py (to be renamed cloudformation.py...) as this was the least verbose.  But IMO the code isn't intuitively obvious to the reader as doing what's conceptually a very simple transform.  Use of ordered dicts to preserve the original XML ordering may be a complicator.

Are there any transformation libraries / techniques in use in moto that might be well used for these functions and result in clearer code?

**Comment by bblommers** [comment]
I'm not aware of any transformation libraries in use @jweite. The current approach is the most used technique for conversions like that.
Some function-level documentation on the nature of the transformation would be enough for me, to help with the clarity.

**Comment by jweite** [comment]
Thanks @bblommers.  I'm in need of better Kinesis and IAM CloudFormation support, which I've started in another branch.   If you've any comments on this work I'd appreciate it, so I can align the other efforts to it.

**Comment by jweite** [comment]
Thanks for the review @bblommers.  Very interested to see how #3201 evolve.

I've been plowing ahead with more complete CloudFormation handling for Kinesis Streams and IAM (needed for a project I'm working, as usual) that builds upon this foundation.  In addition to cloudformation_name_type() and cloudformation_type() 'm consistently adding:

- create_from_cloudformation_json()
- update_from_cloudformation_json()
- delete_from_cloudformation_json()
- @property physical_resource_id()

which are used by the standard cloudformation code (parsing.py).  Perhaps they might go into the CloudFormationModel ABC?

**Comment by jweite** [comment]
Just saw #3201.  Awesome breadth @richford & @bblommers!  I'll rebase my in-progress IAM and Kinesis Cloudformation work on this.  @bblommers, let me know if the s3 work merges cleanly, and if not, I'll wrangle it to be based on 3201 too.

**Pull request merged**
