### PR TITLE
Add ProjectionExpression & ExpressionAttributeNames to DynamoDB get_it…

### LINKED ISSUE #2440: Mock Dynamodb2 does not respect ProjectionExpression in get_item
### Reproduce the bug:

Setup moto:
```
import moto
import boto3
mock = moto.mock_dynamodb2()
mock.start()
```

Create a table:
```
client = boto3.client("dynamodb")
client.create_table(TableName="test"
    , KeySchema=[{"AttributeName": "id", "KeyType": "HASH"}]
    , AttributeDefinitions=[{"AttributeName": "id", "AttributeType": "S"}]
    , ProvisionedThroughput={"ReadCapacityUnits": 1, "WriteCapacityUnits": 1})
```

Insert some data:

```
table = boto3.resource("dynamodb").Table("test")
table.put_item(Item={"id": "abc", "location": "xyz", "TTL": "1570010846"})
```

Now I want to fetch the data, but I don't want the TTL
```
table.get_item(Key={"id": "abc"}, ProjectionExpression='id, location')
```

### Expected Result:

Only the id and location fields should be returned

### Actual Result:

The whole item, including the TTL is returned

### PR DESCRIPTION
**Pull request by gruebel**
…em & batch_get_item

Fixes #2440

I mainly aligned my changes to the same implementation in `query()`.

### CODE REVIEW

**Comment by spulec** [comment]
Thanks; this will be great to add.

Can you refactor the code a bit so there isn't so much code duplication between what already exists in `query` and your new code?

**Comment by gruebel** [comment]
Good point, I will adjust my PR

**Comment by gruebel** [comment]
@spulec I hope, this is how you imagined it. I also changed my tests to use `sure` syntax

**Comment by mikegrima** [comment]
LGTM

**Pull request merged**
