### PR TITLE
3730 update api key - doc update 

### PR DESCRIPTION
**Pull request by rajendersaini**
3730 update api key - doc update

### CODE REVIEW

**Review by bblommers — APPROVED** [review]
Nice one @rajendersaini!

**Comment by bblommers** [comment]
Just noticed that the create/delete_api_key is also missing from the docs - I'll fix that later today

**Comment by rajendersaini** [comment]
Great - thank you for the quick work.

**Comment by rajendersaini** [comment]
@bblommers - kindly bless this pull request.

**Pull request merged**
