### PR TITLE
#1923 Allow to create images with creation date in past (for testing purposes)

### PR DESCRIPTION
**Pull request by Constantin07**
This PR is to address issue reported in #1923.

Reason: In order to test some clean up scripts I need to be able to create in test fixture some AMIs (properly named, tagged, etc.) but with creation date in the past.

The test script checks the datetime of AMI as a criteria what to keep and what to delete.

### CODE REVIEW

**Comment by spulec** [comment]
It isn't clear to me what this changes. Won't it still set the current time as the creation date in the AMI instantiation?

**Comment by Constantin07** [comment]
the idea was to be able to pass `creation_date` value in the past instead of using default (current time).

**Comment by spulec** [comment]
Maybe I'm missing it, but it seems like this change still won't allow you to pass a `creation_date`. Where would you be passing it?

**Comment by spulec** [comment]
Some example code of how you are planning on using this would be very helpful.

**Comment by queue-tip** [comment]
I don't think this PR is necessary. the Ami class in ect/models.py already sets `creation_date` to the current time. For testing, you could import `freeze_time` from freezegun and create images at any point in time. This will only work when not in server_mode.

**Comment by spulec** [comment]
I tend to agree with @queue-tip . I'm going to close this out, but let me know if I am missing something.

**Pull request closed without merging**
