### PR TITLE
ecs.run_task count default to 1

### PR DESCRIPTION
**Pull request by ipmb**
This mimics boto3's undocumented behavior.

### CODE REVIEW

**Review by bblommers — CHANGES_REQUESTED** [review]
Thanks for the PR, @ipmb! Can we get a simple unit test to cover this? Happy to merge after that

**Comment by ipmb** [comment]
Test added. I piggybacked on an existing test to avoid duplicating the code to bootstrap the necessary dependencies.

**Comment by ipmb** [comment]
@bblommers could you take another look at this one? I added a test and updated the branch.

**Review by bblommers — APPROVED** [review]
LGTM! Thanks again @ipmb

**Pull request merged**
