### PR TITLE
fix list-object-versions with prefix

### PR DESCRIPTION
**Pull request by thehesiod**

### CODE REVIEW

**Comment by JackDanger** [comment]
@thehesiod This is great! It needs a test on this behavior before we can merge it. Mind making an attempt at adding a test for this and if you get stuck just push what you have and ask for help here?
I recommend starting around here: https://github.com/thehesiod/moto/blob/e1aa42cf7df129a1bf618e5e599d3e6d30b674a8/tests/test_s3/test_s3.py#L749

**Comment by thehesiod** [comment]
done

**Comment by JackDanger** [comment]
Nice! Great work. Merging.

**Comment by JackDanger** [comment]
It's merged. Thanks for the contribution @thehesiod. Welcome to Moto! :)

**Comment by thehesiod** [comment]
I'm working on a scenario where I have a SNS topic that's supposed to trigger Lambdas, but I'm guessing lambda execution is not supported as that would require moto using docker or something under the covers.  It's unfortunate there doesn't seem to be a botocore API to be able to get SNS notifications, but I saw the trick of hooking a SQS queue to get them that way.  thanks for this module!

**Comment by JackDanger** [comment]
@thehesiod Please share with the Moto community (in an issue or wherever is convenient) whatever setup you come up with. Everybody is trying to solve very similar problems!

**Comment by thehesiod** [comment]
logged https://github.com/spulec/moto/issues/1047

**Pull request merged**
