### PR TITLE
Fix s3bucketpath handling for IP based requests

### PR DESCRIPTION
**Pull request by 2mf**
I've made some additions to the 'Host' field checking to determine whether it is subdomain based or url path based.
With this change it works with plain IP-Addresses.

This partially fixes issue #532

### CODE REVIEW

**Comment by jgelens** [comment]
Great, this fixes our use-case.

**Comment by spulec** [comment]
Thanks

**Comment by leplatrem** [comment]
Thanks for tackling this!

**Comment by rocky4570** [comment]
This change causes problems when using moto on Windows machines as inet_pton is not part of the socket module. 

Results in AttributeError: 'module' object has no attribute 'inet_pton'

Requires installing (win-inet-pton) and placing:

import os
if os.name == 'nt':
    import win_inet_pton
import socket

But this isn't really a good option IMHO, as forces requirements to contain a library for architecture type for  the 1 check being done to determine if sub-domain.

**Pull request merged**
