### PR TITLE
Adds basic implementations for vpc-classic-link and vpc-classic-link-dns-support

### PR DESCRIPTION
**Pull request by wesselvdv**
Implements the following routes:

* describe-vpc-classic-link
* enable-vpc-classic-link
* disable-vpc-classic-link
* describe-vpc-classic-link-dns-support
* enable-vpc-classic-link-dns-support
* disable-vpc-classic-link-dns-support

### CODE REVIEW

**Comment by spulec** [comment]
Code looks good! If we can get the tests passing, will be happy to merge.

**Comment by catherinetcai** [comment]
@wesselvdv Running into this issue now. Wondering if you have any updates. Otherwise, I'd like your permission to update this PR to get rid of the merge conflicts and update the tests.

**Comment by wesselvdv** [comment]
> @wesselvdv Running into this issue now. Wondering if you have any updates. Otherwise, I'd like your permission to update this PR to get rid of the merge conflicts and update the tests.

You have my permission to pick it up further and fix it!

**Comment by catherinetcai** [comment]
@wesselvdv Just wanted to ping you that this is good to go: https://github.com/spulec/moto/pull/2555

**Pull request closed without merging**
