### PR TITLE
Adding ECR

### PR DESCRIPTION
**Pull request by mbjerkness**

### CODE REVIEW

**Comment by JackDanger** [comment]
@mbjerkness This is awesome! Nice work! Let me know if you get stuck on the tests and let's get this merged.

**Comment by JackDanger** [comment]
@mbjerkness Is this ready to merge? It looks great to me

**Comment by mbjerkness** [comment]
@JackDanger I think so. Tests are passing. Unimplemented methods are stubbed out. I have tested it for my own stuff and it has been working great!
:shipit:

**Comment by JackDanger** [comment]
@mbjerkness This is a big help to a lot of people. Thank you so much for your effort on this!

**Comment by spulec** [comment]
This is awesome, thanks @mbjerkness

**Pull request merged**
