### PR TITLE
FIX: Cognito-idp

### PR DESCRIPTION
**Pull request by alastairmccormack**
Minor fixes to cognito-idp:

* Added missing `TokenType` to  all `AuthenticationResults`
* `REFRESH_TOKEN_AUTH` flow is an alias for `REFRESH_TOKEN` flow, so can be handled by the same logic
* During token refresh, access_token and id_token were incorrectly switched

### CODE REVIEW

**Comment by alastairmccormack** [comment]
Unit tests for 3.6 fail in one place - I'm not able to recreate locally. Can this test be re-run?

**Comment by bblommers** [comment]
Restarting the build resulted in even more failures - looks like the CI is a bit unstable ATM.
Will try to restart it again later.

**Review by bblommers — CHANGES_REQUESTED** [review]
Would you mind merging in master @alastairmccormack? The latest changes should fix the build, I'd be happy to merge once that happens

**Review by bblommers — APPROVED** [review]
LGTM! Thanks @alastairmccormack

**Pull request merged**
