### PR TITLE
SES Enhancement Adding  get_send_statistics,create_configuration_set functions.

### PR DESCRIPTION
**Pull request by usmangani1**
https://github.com/localstack/localstack/issues/909

Enhancement Adding SES get_send_statistics,create_configuration_set functions.

### CODE REVIEW

**Comment by usmangani1** [comment]
> [localstack/localstack#909](https://github.com/localstack/localstack/issues/909)
> 
> Enhancement Adding SES get_send_statistics,create_configuration_set functions.

@bblommers  Need your help here in getting this merged.Can you please help.

**Comment by usmangani1** [comment]
> > [localstack/localstack#909](https://github.com/localstack/localstack/issues/909)
> > Enhancement Adding SES get_send_statistics,create_configuration_set functions.
> 
> @bblommers Need your help here in getting this merged.Can you please help.

@bblommers can u help me here please ?

**Comment by TonyZZX** [comment]
Hi, can I know which version is the minimum requirement to use this feature?

**Comment by bblommers** [comment]
Hi @TonyZZX, the full list of versions can be found here: https://pypi.org/project/moto/#history

Considering this was merged on the 4th of May, it should be available as of moto >= 1.3.15.dev815

**Pull request merged**
