### PR TITLE
Add support for NoncurrentVersionTransition, NoncurrentVersionExpiration, and AbortIncompleteMultipartUpload actions to S3 lifecycle rules

### LINKED ISSUE #1845: S3 lifecycle configuration missing AbortIncompleteMultipartUpload attribute
Current S3 model does not return the AbortIncompleteMultipartUpload attribute in the lifecycle configuration response.

This prevents us from using moto to validate scripts involving the AbortIncompleteMultipartUpload parameter on S3 bucket lifecycles.

### PR DESCRIPTION
**Pull request by jrbeilke**
Resolves #1845 (adds AbortIncompleteMultipartUpload), and also adds support for NoncurrentVersionTransition and NoncurrentVersionExpiration lifecycle actions in S3.

### CODE REVIEW

**Comment by jrbeilke** [comment]
Seems one of the tests in the the travis build failed due to a timing issue with an unrelated test for dhcp_options:
```
======================================================================
FAIL: Failure: AssertionError (given
X = datetime.datetime(2018, 10, 5, 16, 47, 59, tzinfo=tzlocal())
    and
Y = datetime.datetime(2018, 10, 5, 16, 48, tzinfo=tzlocal())
X != Y)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/spulec/moto/tests/test_ec2/test_elastic_block_store.py", line 593, in <module>
    @mock_ec2
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/freezegun/api.py", line 615, in freeze_time
    return freeze_time(time_to_freeze(), tz_offset, ignore, tick)
  File "/home/travis/build/spulec/moto/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "/home/travis/build/spulec/moto/tests/test_ec2/test_elastic_block_store.py", line 623, in test_copy_snapshot
    getattr(source, attrib).should.equal(getattr(dest, attrib))
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/sure/__init__.py", line 387, in wrapper
    raise AssertionError(e)
AssertionError: given
X = datetime.datetime(2018, 10, 5, 16, 47, 59, tzinfo=tzlocal())
    and
Y = datetime.datetime(2018, 10, 5, 16, 48, tzinfo=tzlocal())
X != Y
>>  raise AssertionError(AssertionError(u'given\nX = datetime.datetime(2018, 10, 5, 16, 47, 59, tzinfo=tzlocal())\n    and\nY = datetime.datetime(2018, 10, 5, 16, 48, tzinfo=tzlocal())\nX != Y',))
```

I did have a successful build in travis from my own fork:
https://travis-ci.org/jrbeilke/moto/builds/437699776

**Comment by jrbeilke** [comment]
Found the source of the test failure. In EC2 test_copy_snapshot() a snapshot is created, then subsequently copied, and the attributes of the two snapshots are compared.

Based on log I posted in my previous comment it appears that there was a second between creating and copying the snapshots during the test, which resulted in two different start_time values and the failure of the test.

Seems like test_copy_snapshot() should be updated to not compare the start_time attributes between the snapshots as there's no guarantee (or expectation) that the values will be the same for both snapshots. Pushing an update to my branch with this change.

**Comment by jrbeilke** [comment]
Looks like there was another unrelated test error in travis with test_elbv2.test_create_target_groups_through_cloudformation this time, but only with Python 3.6 in TEST_SERVER_MODE.

Unfortunately it's not clear in the logs why the test failed:
```
======================================================================
FAIL: test_elbv2.test_create_target_groups_through_cloudformation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/spulec/moto/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "/home/travis/build/spulec/moto/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "/home/travis/build/spulec/moto/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "/home/travis/build/spulec/moto/tests/test_elbv2/test_elbv2.py", line 1588, in test_create_target_groups_through_cloudformation
    ) == 2
AssertionError: 
```

**Comment by spulec** [comment]
This is great, thanks!

**Pull request merged**
