### PR TITLE
Add If-Match, If-None-Match and If-Unmodified-Since to S3 GET/HEAD

### LINKED ISSUE #2705: HeadObject validation does not honor all validation parameters
Hi! This issue appears related to https://github.com/spulec/moto/issues/2263

**Observed Behavior**
I'm using `unittest` to write a test that will ensure validation on HeadObject calls work as expected. My `setUp` function includes the following code:
```python3.7
TEST_BUCKET = "fake_bucket"
TEST_KEY = "fake.csv"

@mock_s3
class TestVerifyS3Object(unittest.TestCase):
    def setUp(self):
        # Some other code ...
        self.s3_client = boto3.client("s3", region_name="us-east-1")
        self.s3_client.create_bucket(Bucket=TEST_BUCKET)
        self.s3_client.upload_file(Filename=tmp_file, Bucket=TEST_BUCKET, Key=TEST_KEY)
```

My unit tests have attempted both of the following:
```python3.7
        with self.assertRaises(botocore.exceptions.ClientError):
            self.s3_client.head_object(Bucket=TEST_BUCKET, Key=TEST_KEY, IfMatch="foo")
```
and
```python3.7
        with self.assertRaises(botocore.exceptions.ClientError):
            self.s3_client.head_object(
                Bucket=TEST_BUCKET, Key=TEST_KEY, IfUnmodifiedSince=datetime.datetime.utcnow())
```
Both result in `AssertionError: ClientError not raised`
I am invoking the tests locally using `nose==1.3.7`, and using `moto==1.3.14` which I installed using `pip`.

**Expected Behavior**
When I run the function I'm testing in a real environment using `boto==2.49.0`, `boto3==1.11.8`, and `botocore==1.14.9`, this code raises a `botocore.exceptions.ClientError`:
```python3.7
In [17]: try:
    ...:     client.head_object(
    ...:         Bucket=TEST_BUCKET, Key=TEST_KEY, IfMatch="foo",
    ...:     )
    ...: except botocore.exceptions.ClientError as e:
    ...:     print(e)
    ...:
An error occurred (412) when calling the HeadObject operation: Precondition Failed
```
This error response also happens when I execute this code in a lambda.

**Suspected Reason**
I did a little digging and have one idea as to why. I am admittedly not too familiar with this codebase but I hope this is helpful: 

The [`_key_response_head`](https://github.com/spulec/moto/blob/master/moto/s3/responses.py#L1114) method only looks at the `If-Modified-Since` header in the request, when actually there are [several validation headers](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.head_object) that may be passed to the `head_object` operation.

**If so...**
If this is the case, then I imagine something similar to https://github.com/spulec/moto/pull/2276/files would be necessary. If it is that simple, I'd be willing to take this on.

Thanks for reading!

### PR DESCRIPTION
**Pull request by arcivanov**
fixes #2705

### CODE REVIEW

**Comment by arcivanov** [comment]
This is ready for review.

**Comment by arcivanov** [comment]
> Hi @arcivanov, thanks for your PR! The changes look good to me.
Linting fixed, but the tests don't pass in server mode because 412 appears instead of PreconditionFailed:

```
======================================================================
FAIL: tests.test_s3.test_s3.test_boto3_head_object_if_match
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/spulec/moto/moto/core/models.py", line 98, in wrapper
    result = func(*args, **kwargs)
  File "/home/travis/build/spulec/moto/tests/test_s3/test_s3.py", line 2406, in test_boto3_head_object_if_match
    e.response["Error"]["Code"].should.equal("PreconditionFailed")
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/sure/__init__.py", line 387, in wrapper
    raise AssertionError(e)
AssertionError: given
X = '412'
    and
Y = 'PreconditionFailed'
X is '412' whereas Y is 'PreconditionFailed'
>>  raise AssertionError(e)
```

It looks like the issue is disagreement between the server mode and the boto3 patching mode. I don't know if you want me to try to fix this in this PR as well.

**Comment by arcivanov** [comment]
I also left some questions/notes in gitter: https://gitter.im/awsmoto/Lobby?at=5ecad40bb101510b2014983b

**Comment by arcivanov** [comment]
@bblommers bump?

**Comment by bblommers** [comment]
@spulec Do you have any idea why a 412 response would behave differently in server mode?
It feels very similar to https://github.com/pallets/werkzeug/issues/1231, but that is supposedly fixed

**Comment by arcivanov** [comment]
@spulec bump

**Comment by arcivanov** [comment]
@spulec bump again

**Comment by arcivanov** [comment]
@spulec and again a bump

**Comment by arcivanov** [comment]
@spulec @bblommers bumping again for guidance.

**Comment by spulec** [comment]
So it looks like the current exception system we have relies on sending an XML response body, which botocore then parses.

Since these are HEAD requests though, Werkzeug is correctly eating the response and sending back an empty body. That is what is causing the issue.

So I guess the question is what AWS does on these HEAD errors? Are there additional response headers they add with details? We should figure out what their response looks like and mimic that.

**Comment by arcivanov** [comment]
> So I guess the question is what AWS does on these HEAD errors? Are there additional response headers they add with details? We should figure out what their response looks like and mimic that.

Would you like me to do it or you're contemplating doing it yourself? Just so it doesn't become an abstract "someone" :smile:

**Comment by spulec** [comment]
If you have some time and can take a look, that would be great. I probably won't be able to prioritize this in the near future.

**Comment by arcivanov** [comment]
@spulec I just confirmed that 304 on a GET with `If-Modified-Since` gives you empty body.

**Comment by arcivanov** [comment]
@spulec PreconditionFailed looks like this:

```
2020-09-07 00:06:21,608 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amz-request-id': 'YYYYYYYYY', 'x-amz-id-2': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'Content-Type': 'application/xml', 'Transfer-Encoding': 'chunked', 'Date': 'Mon, 07 Sep 2020 04:06:21 GMT', 'Server': 'AmazonS3'}
2020-09-07 00:06:21,608 - MainThread - botocore.parsers - DEBUG - Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>PreconditionFailed</Code><Message>At least one of the pre-conditions you specified did not hold</Message><Condition>If-Unmodified-Since</Condition><RequestId>ZZZZZZZZZZZZZZZ</RequestId><HostId>XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=</HostId></Error>'
```

**Comment by arcivanov** [comment]
@spulec > Since these are HEAD requests though

Actually these are not HEAD requests. The tests added only touch GET requests and the tests fail on them. Notice that the tests only test GET verbs:

https://github.com/spulec/moto/pull/3021/files#diff-7d7d6e11280db33d038b8cb9a4180feaR2328

**Comment by spulec** [comment]
The two tests that are failing on Travis are the newly added `test_boto3_head_object_if_unmodified_since` and `test_boto3_head_object_if_match` which both call `s3.head_object(...)`

Screen Shot 2020-09-07 at 10 47 49 AM

**Comment by arcivanov** [comment]
@spulec You're quite right, sorry it was late in the night. Let me get the dumps for that.

**Comment by arcivanov** [comment]
head-object with `if-unmodified-since`
```
2020-09-07 13:27:12,302 - MainThread - urllib3.connectionpool - DEBUG - https://url:443 "HEAD /file HTTP/1.1" 412 0
2020-09-07 13:27:12,303 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amz-request-id': 'XXXXXXXXX', 'x-amz-id-2': 'yyyyyyyyyy', 'Content-Type': 'application/xml', 'Transfer-Encoding': 'chunked', 'Date': 'Mon, 07 Sep 2020 17:27:11 GMT', 'Server': 'AmazonS3'}
2020-09-07 13:27:12,303 - MainThread - botocore.parsers - DEBUG - Response body:
b''
```

**Comment by arcivanov** [comment]
head-object with `if-modified-since`

```
2020-09-07 13:30:19,705 - MainThread - urllib3.connectionpool - DEBUG - https://url "HEAD /file HTTP/1.1" 304 0
2020-09-07 13:30:19,706 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amz-id-2': 'xxxxxxx', 'x-amz-request-id': 'yyyyyy', 'Date': 'Mon, 07 Sep 2020 17:30:20 GMT', 'Last-Modified': 'Thu, 03 Sep 2020 15:50:49 GMT', 'ETag': '"nnnnnnnnnnnnnn"', 'Server': 'AmazonS3'}
2020-09-07 13:30:19,707 - MainThread - botocore.parsers - DEBUG - Response body:
b''
```

**Comment by arcivanov** [comment]
Fixed! @spulec @bblommers

**Comment by arcivanov** [comment]
Bump!

**Comment by arcivanov** [comment]
Bump!

**Review by bblommers — APPROVED** [review]
LGTM. Thanks @arcivanov!

**Pull request merged**
