### PR TITLE
MultiAccount support

### PR DESCRIPTION
**Pull request by bblommers**
TODO:

 - [x] Documentation: https://moto--5192.org.readthedocs.build/en/5192/docs/multi_account.html
 - [x] Determine account ID based on provided aws_access_key
 - [x] Use account ID to select the correct backend
 - [x] Use account ID everywhere, instead of `get_account_id`
 - [x] Add tests for STS usecase
 - [x] Add tests for Environment Variable usecase
 - [x] change scaffold to use backend[account_id][region]
 - [x] Fix server tests - needs to pass an account ID
 - [x] Add more tests - verify that requests to different accounts are separated 
 - [x] fix ServerMode tests - needs to find this account ID 
 - [x] Update docs with the option to add a request-header
 - [x] Look into performance issues

### CODE REVIEW

**Comment by bblommers** [comment]
@thrau @whummer A WIP to properly implement multi-account support.

Note that the current documentation describes how I'm envisioning this to work, but I haven't looked at the technical feasibility yet.

What would be the best way to expose this functionality to Localstack - is the environment variable enough? Would it be useful to have a dedicated API within Moto to manage accounts?

**Comment by getsec** [comment]
This PR looks awesome, super excited to test and try this out! If you need anything or someone to help validate and test, Im all ears.

**Comment by getsec** [comment]
@bblommers 
I had some spare time today to play around with the work you have done. From my few small tests, things are working great. Ideally I want to run a bunch of tests where AMI's are shared with child accounts, and validate that this works as we design. Previously, I could not do this with as the `OwnerId` field would not update (always being the default `123456789012`). Thanks to the work you did, my small test shows some good outcome!

```py
import unittest
import boto3
import os

from moto import mock_ec2


EXAMPLE_AMI_ID = "ami-12c6146b"

@mock_ec2
class test(unittest.TestCase):
    # class method to create an AWS AMI with boto3
    def _ami(client):
        x = client.run_instances(ImageId=EXAMPLE_AMI_ID,
                                 InstanceType='t2.micro',
                                 MinCount=1,
                                 MaxCount=1)

        instance_id = x['Instances'][0]['InstanceId']
        image = client.create_image(InstanceId=instance_id, Name='test_image')
        desc = client.describe_images(ImageIds=[image['ImageId']])
        return desc
    
    def test_one(self):
        #Create a bucket in the default account
        client = boto3.client('ec2')
        image_id1 = self._ami(client)

        os.environ["MOTO_ACCOUNT_ID"] = "111111111111"
        client = boto3.client('ec2')
        image_id2 = self._ami(client)
        os.environ["MOTO_ACCOUNT_ID"] = "111111111111"
   
        
        self.assertNotEqual(image_id1['Images'][0]['OwnerId'], 
                            image_id2['Images'][0]['OwnerId'])

```

Test outcome is correct as well!

```
❯ pytest
test_main.py .                 [100%]

===== 1 passed in 0.83s =========
```

Obviously this isn't my entire plan, I'm hoping to have some more time this and next week to fully test out the entire process! Will report results!

PS; I was able to install your version via `pip install git+ssh://git@github.com/bblommers/moto.git@feature/multi-account-support`, is this the best way for this, or is there an alternative to this installation method. 

Anyways, thanks a bunch for all your hard work

**Comment by bblommers** [comment]
> is this the best way for this, or is there an alternative to this installation method.
>

@getsec As far as I know, that is the best and easiest way to test these changes, yes. Thanks for the feedback so far!

**Comment by getsec** [comment]
@bblommers  🥳 Awesome work!

**Comment by lorengordon** [comment]
Just saw the release, this is great! Thanks!

**Pull request merged**
