### PR TITLE
bugfix codepipeline handling iam trust policies and absence of tags.

### PR DESCRIPTION
**Pull request by pvbouwel**
Add a test where a valid trust policy is provided but where tests will fail and add a test where no tags are provided which will fail with the current code.
A commit will be added afterwards to make the tests green.

### CODE REVIEW

**Comment by pvbouwel** [comment]
For some reason moto server doesn't come up in the test environment. Locally I can start it without an issue, so it doesn't immediately seem related to my PR.

The test_codepipeline folder didn't had an __init__.py and seemed that it was disabled but generally since that is test code that shouldn't influence moto server's capability to get up and running as it is only test related code in there.

**Comment by bblommers** [comment]
The failures are unrelated @pvbouwel - the `werkzeug` dependency released a new version that broke our builds.

Would you mind merging in the latest master? That should fix everything

**Comment by pvbouwel** [comment]
Thanks for the info

Since I don't have dependencies on this yet I just rebased my changes to keep commit history clean. 
I see server starts now so :crossed_fingers: for a green build.

**Review by bblommers — APPROVED** [review]
Nice one - thanks for the PR @pvbouwel!

**Pull request merged**
