### PR TITLE
adding physical_resource_id in SubnetRouteTableAssociation, Route and NatGW classes

### PR DESCRIPTION
**Pull request by ismferd**
Adding physical_resource_id in SubnetRouteTableAssociation, Route and NatGW classes in `moto/ec2/models.py` in order to avoid https://github.com/localstack/aws-cdk-local/issues/44

### CODE REVIEW

**Review by bblommers — CHANGES_REQUESTED** [review]
Hi @ismferd, thanks for the PR!
Would you mind adding some tests, to verify this works properly?
Looks like the linter fails as well at the moment - you can run `make lint` to verify whether the formatting is correct

**Comment by ismferd** [comment]
Hi @bblommers ,

I can't see the linter issue at local as you could see below:
image

**Comment by bblommers** [comment]
Which version of black are you using?
The latest has some bugs, so we're using `black==19.10b0`

**Comment by ismferd** [comment]
🥳

**Review by bblommers — APPROVED** [review]
LGTM! Thanks again @ismferd

**Comment by bblommers** [comment]
This is now part of moto >= 2.0.3.dev8

**Pull request merged**
