### PR TITLE
Python 3.8 support

### PR DESCRIPTION
**Pull request by yan12125**
Enable tests on Python 3.8 and fix them.

### CODE REVIEW

**Comment by bblommers** [comment]
Exploratory question @mikegrima: would it make more sense to drop support for 2.7? 
- It'lll be EOL in two months
- Based on this survey, much more people use 3.6 than 2.7: https://www.jetbrains.com/research/python-developers-survey-2018/

**Comment by spulec** [comment]
Let's punt on dropping anything for now. I'd like to see if we can get some more data on usage first.

**Comment by spulec** [comment]
This looks great; thank you!

**Comment by baolsen** [comment]
The "make lint" checks only run when Python == 3.7. 
Should this be changed to include checks for 3.8?

**Pull request merged**
