### PR TITLE
Do not freeze requirement aws-xray-sdk to a specific version 

### PR DESCRIPTION
**Pull request by frivoire**
Use '>=' instead of '==' to allow future versions to be updated.
cf https://github.com/spulec/moto/issues/1290

### CODE REVIEW

**Comment by JackDanger** [comment]
Thanks for the fix, @frivoire! Welcome to Moto! :)

**Comment by JackDanger** [comment]
This is now released as Moto 1.1.24

**Comment by frivoire** [comment]
Thanks !!

NB: one minor thing : the git tag for 1.1.24 doesn't appear on github : 
https://github.com/spulec/moto/releases

**Comment by JackDanger** [comment]
Thanks, @frivoire - fixed!

**Pull request merged**
