### PR TITLE
sns#create_platform_endpoint: If token and attributes are the same, return endpoint

### PR DESCRIPTION
**Pull request by kohbis**
#4056

### CODE REVIEW

**Review by bblommers — CHANGES_REQUESTED** [review]
Hi @kohbis, thanks for the PR! Would you mind adding a test for this as well, in tests/test_sns/test_application_boto3.py?

There is already a test to verify the duplicate exception, so that might need adjusting as well

**Comment by kohbis** [comment]
Hi @bblommers, thanks for confirming the PR. I've added & updated tests.
https://github.com/spulec/moto/pull/4055/commits/5d49275791978177126dcc4fea702aab04d62660
I was wondering if you could check them !

**Review by bblommers — APPROVED** [review]
LGTM - thanks for the PR @kohbis!

**Comment by kohbis** [comment]
thanks for review&merge!

**Pull request merged**
