### PR TITLE
Sagemaker support

### LINKED ISSUE #2124: Adding support for AWS Sagemaker
Adding initial support for sagemaker model endpoints

### PR DESCRIPTION
**Pull request by porthunt**
Solves flake8 errors from #2125.

Resolves #2124

### CODE REVIEW

**Comment by porthunt** [comment]
The tests are broken. I'll fix them tomorrow morning.

**Comment by jweite** [comment]
I've just finished coding most of the notebook instance methods in my own fork.  Since you got here first, I set up a similar foundation, so they should merge smoothly.  I need these model methods for my project (and will need endpoint, endpoint config and training job soon).  Let me know if/how we can collaborate.

**Comment by porthunt** [comment]
@jweite Nice! I also need the notebook instances method for my project, so that's pretty handy. I would say you can create a new PR with the commits from here and we close this one then?

Regarding the tests, they are passing now, but when `TEST_SERVER_MODE` is set to `True`, they break. It's seems to be something related to the raised errors, but I didn't have time to investigate it deeply.

**Comment by bblommers** [comment]
@porthunt The ServerMode tests are currently failing due to an [unrelated issue](https://github.com/spulec/moto/issues/3098), so I'd say ignore those for now

**Comment by jweite** [comment]
@porthunt, I've created the new PR with our combined work: https://github.com/spulec/moto/pull/3105.

Note that I changed two things in the Models: returning the model's arn (not its execution role's), and raising ValidationError when requested model is not found.

**Comment by porthunt** [comment]
Clsoing this PR.

**Pull request closed without merging**
