### PR TITLE
adds tagging support for cloudwatch events service

### PR DESCRIPTION
**Pull request by bryanlalexander**
The CloudWatch events service lacks tagging support. This causes Terraform to fail when executing against a running moto server.

This pull request updates the following:
- Adds `TaggingService` (a generic implementation of tagging for easing the adoption of tagging support across moto)
- Implements tagging for CloudWatch events using `TaggingService`
- removes duplicate `test_list_rules` in `test_events.py`

### CODE REVIEW

**Comment by brady-gsa** [comment]
@bblommers @spulec @JackDanger 

Does this look ready to merge?

**Comment by bblommers** [comment]
Looks good to me - I like the idea of having a single tagging service that can be reused. Just noting that we'll need to rework this into all services, not just events - that might take a while.

Do we need to untag resources automatically when the resource is deleted?

Leaving this open for a second review by someone

**Comment by bryanlalexander** [comment]
@bblommers do we need to do anything further at this point? We've got another PR in the wings that we will be re-basing on this commit after it is merged.

**Comment by brady-gsa** [comment]
@bblommers can this one be merged as well? We are going to re-base our third pull request off this one once it's merged.

**Comment by brady-gsa** [comment]
@bblommers I updated the tests to use sure and changed it to untag when resources are deleted. Can this be merged? 

Also, is there anyone else not tagged on this pull with write access to the moto repo?

**Comment by bblommers** [comment]
Hi @brady-gsa, looks good to me, but we do need another maintainer to review/approve this though. I've tagged @mikegrima as well.

**Comment by brady-gsa** [comment]
Thanks @bblommers. @mikegrima @JackDanger @spulec I know you are all probably busy but we'd appreciate if one of you can take a moment to review so we can move on to our other pull request which adds tagging to another service as well. Thanks!

**Comment by spulec** [comment]
Looks great. Thanks for all of the work and welcome to Moto!

**Pull request merged**
