### PR TITLE
Added policy tagging that was previously marked as missing

### LINKED ISSUE #4519: IAM policy tagging not implemented
Tagging on IAM policies is missing so I wish to add support for it.

### How to reproduce
---
To reproduce, I attempted to use the following python code:

```python
iam_client = boto3.client('iam')

managed_policy = {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "S3ReadOnly",
            "Effect": "Allow",
            "Action": [
                "s3:Get*",
                "s3:List*"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Sid": "Ec2FullAccess",
            "Action": "ec2:*",
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}

PolicyTags = [
    {
    'Key' : 'BaselineProtected',
    'Value': 'IAMPolicy'
    },
]

iam_client.create_policy(
    PolicyName='Test-policy'
    PolicyDocument=json.dumps(managed_policy)
)  

iam_client.tag_policy(
    PolicyArn="arn:aws:iam::123456789012:policy/Test-policy,
    Tags=PolicyTags
)
```

### Expected behaviour
---
IAM policy would be created and tags added.

### What actually happens
---
I receive the error: `NotImplementedError: The tag_policy action has not been implemented`

### What version of moto am I using
---
```
boto                   2.49.0
boto3                  1.19.5
botocore               1.22.5
moto                   2.2.13.dev0
```

### How it might be fixed
---
I will submit a PR with the code required, using IAM roles tagging as a template.

### PR DESCRIPTION
**Pull request by Munkfeister**
Resolves #4519

This PR includes everything required to implement IAM policy tagging.

The PR uses IAM role tagging as a template so should cover all required aspects. Tests have been run locally and appear to be successful.

### CODE REVIEW

**Review by bblommers — CHANGES_REQUESTED** [review]
Hi @Munkfeister, thanks for the test!
Would you mind adding tests for these features? Existing policy tests [can be found here](https://github.com/spulec/moto/blob/master/tests/test_iam/test_iam_policies.py) - let me know if you need any pointers

**Comment by Munkfeister** [comment]
> Hi @Munkfeister, thanks for the test! Would you mind adding tests for these features? Existing policy tests [can be found here](https://github.com/spulec/moto/blob/master/tests/test_iam/test_iam_policies.py) - let me know if you need any pointers

Hi @bblommers, thanks for the comment.  I've added the following tests to `test_iam.py` already:

test_create_policy_with_tags
test_tag_policy
test_untag_policy

These were simply based on the existing tests for IAM roles.

If further tests are required, some pointers would be great if that's ok with you?

**Comment by bblommers** [comment]
> 
> If further tests are required, some pointers would be great if that's ok with you?

Ah, my bad - I didn't see the tests for some reason the first time.
Only comment I've got that it would be great to split the tests, and let each method have a single responsibility. Having a single method that tests multiple things (successful tagging, failure because of x, failure because of y, ..) makes debugging them a lot more difficult.

**Comment by Munkfeister** [comment]
> > If further tests are required, some pointers would be great if that's ok with you?
> 
> Ah, my bad - I didn't see the tests for some reason the first time. Only comment I've got that it would be great to split the tests, and let each method have a single responsibility. Having a single method that tests multiple things (successful tagging, failure because of x, failure because of y, ..) makes debugging them a lot more difficult.

No worries! I've just fixed a linting issue I missed.

I agree with you regarding the splitting of the tests. Is that something you'd want done prior to the pull request completion? Might be worth doing the same for the IAM roles I based the tests on, so I could raise a separate issue for that if you like?

**Comment by bblommers** [comment]
> 
> No worries! I've just fixed a linting issue I missed.
> 
> I agree with you regarding the splitting of the tests. Is that something you'd want done prior to the pull request completion?

Yes, please. The code itself looks fine to me, it's really just the tests.

> 
> Might also be worth doing the same for the IAM roles I based the tests on, so I could raise a separate issue for that if you like?

That would be very welcome! A code cleanup is always appreciated.

**Comment by Munkfeister** [comment]
> > No worries! I've just fixed a linting issue I missed.
> > I agree with you regarding the splitting of the tests. Is that something you'd want done prior to the pull request completion?
> 
> Yes, please. The code itself looks fine to me, it's really just the tests.
> 
> > Might also be worth doing the same for the IAM roles I based the tests on, so I could raise a separate issue for that if you like?
> 
> That would be very welcome! A code cleanup is always appreciated.

Awesome! I've just committed a change with the tests split up and requested a re-review. Hope that's ok?

**Review by bblommers — APPROVED** [review]
LGTM! Thanks again for the PR @Munkfeister

**Pull request merged**
