### PR TITLE
iam - add RoleLastUsed to get_role response

### PR DESCRIPTION
**Pull request by kentnsw**

### CODE REVIEW

**Comment by kentnsw** [comment]
Hi, could anyone shed some light on this? I've no idea why python 3.6 is not happy about it. After all, >=3.7 are happy.
```
=================================== FAILURES ===================================
___________________ test_get_role__should_contain_last_used ____________________
    @mock_iam
    def test_get_role__should_contain_last_used():
        conn = boto3.client("iam", region_name="us-east-1")
        conn.create_role(
            RoleName="my-role", AssumeRolePolicyDocument="some policy", Path="/"
        )
        role = conn.get_role(RoleName="my-role")["Role"]
        role["RoleLastUsed"].should.equal({})
        iam_backend = get_backend("iam")["global"]
        last_used = datetime.strptime(
            "2015-04-09T15:03:43+00:00", "%Y-%m-%dT%H:%M:%S+00:00"
        )
        region = "us-west-1"
>       iam_backend.roles[role["RoleId"]].last_used = last_used
E       KeyError: 'n7cm80tjhjusyrjgk0yb'

tests/test_iam/test_iam.py:94: KeyError
```

**Comment by kentnsw** [comment]
Could someone please restart the tests? I think the failed cases are not related to the changes.

**Comment by bblommers** [comment]
> Hi, how can I setup python 3.6 env locally for testing? It reports `boto3 requires Python '>= 3.7' but the running Python is 3.6.15`. Thanks.

Apologies for the late response @kentnsw. As far as I know, that's a matter of downgrading boto3 - [the last version that supported Python 3.6 was 1.23.10](https://pypi.org/project/boto3/1.23.10/).

**Review by bblommers — APPROVED** [review]
LGTM! Thanks for this PR @kentnsw

**Pull request merged**
