### PR TITLE
Revert "Import time reduction"

### PR DESCRIPTION
**Pull request by asherf**
Breaks importing backend.
See 
https://github.com/spulec/moto/pull/2697#issuecomment-621300975
Reverts spulec/moto#2697

### CODE REVIEW

**Comment by asherf** [comment]
Screen Shot 2020-04-29 at 8 55 37 AM

this revert fixes the issue.

**Comment by asherf** [comment]
FWIW, since this library is mostly used in tests, I don't think load time is such a big issue.
The perf issue can be somewhat mitigated by eagerly loading moto and triggering expensive import in test suite initialization.

The added complexity and risk of doing local imports is not worth it in this case.
just me 2c.

**Comment by bblommers** [comment]
@asherf I've created this PR to fix the problem #2938, which has now been merged.
Would you mind pulling master and verifying that the problem is now fixed?

**Comment by bblommers** [comment]
> 
> 
> FWIW, since this library is mostly used in tests, I don't think load time is such a big issue.


I agree it's not a big issue @asherf  - definitely classifies as a nice to have. Quick feedback is always good though, and I personally quite like the fact I don't have to wait 3/4 secs for a single unit test.

As far as local imports go - I'd like to think that our test coverage is good enough to catch most issues. (And yes, I realize the irony of that statement, considering the context of this conversation.. :) )

It did highlight the fact that there is space for structural improvements! Still thinking of a way to remove the local imports here, and remove the cyclical dependency altogether.

**Pull request closed without merging**
