### PR TITLE
Fix:SQS Receive Message (MessageAttributes) in response

### PR DESCRIPTION
**Pull request by usmangani1**
Fix:SQS Receive Message (MessageAttributes) in response

https://github.com/localstack/localstack/issues/2965

### CODE REVIEW

**Review by bblommers — CHANGES_REQUESTED** [review]
Hi @usmangani1, looks like the tests are failing: https://travis-ci.org/github/spulec/moto/builds/725852437

Can we keep the tests untouched? It should be fine to call receive_message without the new param, and the existing tests already cover that.
This just need additional tests to verify that the functionality of the new param

**Comment by usmangani1** [comment]
> Hi @usmangani1, looks like the tests are failing: https://travis-ci.org/github/spulec/moto/builds/725852437
> 
> Can we keep the tests untouched? It should be fine to call receive_message without the new param, and the existing tests already cover that.
> This just need additional tests to verify that the functionality of the new param

@bblommers  modified existing tests a bit as we are asserting the attributes to be present in the result.After this change we will receive the message attributes in the response only when explicitly requested hence we had to modify the existing tests.

**Review by bblommers — APPROVED** [review]
Thanks @usmangani1!

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.16.dev47

**Pull request merged**
