### PR TITLE
DirectoryService: Add support for other directories

### PR DESCRIPTION
**Pull request by kbalk**
Adds support for the APIs:

- `create_microsoft_ad()`
- `connect_directory()`
- `create_alias()`
- `enable_sso()`
- `disable_sso()`

### CODE REVIEW

**Comment by kbalk** [comment]
@bblommers I have a lot of validation steps in this code.  The steps and logic is not organized that well and the logic takes up a lot of space in `models.py`.  I could make the validation functions individual validations using static methods in the Directory class.   Or I could create a bunch of separate functions and move them to a new file, say `validation.py` or `utils.py`.  Or create a separate Validations class in a separate file?  Do you have a preference or an alternative suggestion?  

It's an issue I've come up against before, so it'd be nice to have a better approach, otherwise `models.py` can get pretty large.

**Comment by bblommers** [comment]
@kbalk No preference here! Having the validation code separated out from `models.py` would indeed by good, but I trust your judgement in how that's done exactly.

**Comment by kbalk** [comment]
I've got a Terraform script that creates an AD Connector and the script fails with my moto code.  I'm debugging the problem and it's taking me some time.  The other thing I have left to do is reorganize the validation.  So it may be a day or two before this code is ready for review.

**Comment by kbalk** [comment]
@bblommers The rearrangement of the validation handling is not ideal, but it feels a little less messy.  

I discovered I was not setting the DnsIpAddrs field, so that was causing the terraform script to fail.  My calculation of those IPs is not great, but it was the best I could do with the knowledge I have.  If someone has a better solution, I hope they change the code.

**Review by bblommers — APPROVED** [review]
LGTM! Thanks for the PR @kbalk

**Pull request merged**
