### PR TITLE
ELBv2 improvements

### LINKED ISSUE #4711: Feature Request ELBv2 Add and Remove Listener Certificates
Please can I request the following features are added to the ELBv2 service.
1. Replace a listener default certificate using the modify_listener function.

```
response = self.client.modify_listener(
  Certificates=[
          {
              'CertificateArn': 'string'
          },
      ],
  ListenerArn='string'
)
```

### PR DESCRIPTION
**Pull request by bblommers**
Closes #4711 

Improvements:
 - Add ProtocolVersion to the response (defaults to HTTP1)
 - Expand the number of valid protocols inline with what AWS considers valid atm
 - Move modify_target_group_attributes to `models.py` - no logic changes
 - Fixes a bug so that certificates are always persisted after a `modify_target_group`. (Before, they were only persisted if the protocol was changed to `HTTPS` at the same time

### CODE REVIEW

**Comment by rickbowden** [comment]
Hi, even after upgrading to version 3.0.3.dev4 I still get an exception when attempting to attach a certificate using the ModifyListener operation.

botocore.errorfactory.CertificateNotFoundException: An error occurred (CertificateNotFound) when calling the ModifyListener operation:

The certificate I am attempting to attach is an IAM server certificate, and not an ACM certificate.

**Comment by bblommers** [comment]
Thanks for letting us know @rickbowden - we'll change the logic here to also accept IAM certificates

**Comment by bblommers** [comment]
This should now be fixed as of moto >= 3.0.3.dev7 @rickbowden - with #4823 merged we now accept IAM certificates as well.
Can you verify this fixes your problem?

**Comment by rickbowden** [comment]
@bblommers I've tested this and it works now. Thanks very much for sorting this.

**Pull request merged**
