### PR TITLE
fix route table association by internet gateway

### PR DESCRIPTION
**Pull request by tony-dot-sh**
fix route table association by internet gateway per https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AssociateRouteTable.html

### CODE REVIEW

**Review by bblommers — CHANGES_REQUESTED** [review]
Hi @tony-dot-sh, thanks for the PR! 
Would you mind adding some tests, to verify that we can call this method now with either parameter?

**Comment by tony-dot-sh** [comment]
Added an IGW test here 6eced35de25a398b7b1bf7c61d8f97a9dcf5f1bc and subnet test here f739b95b3c397649bbdfcc71e6d4e9504b70ac2f

**Review by bblommers — APPROVED** [review]
LGTM

**Comment by bblommers** [comment]
This is now part of moto >= 2.0.3.dev3

**Pull request merged**
