### PR TITLE
Improved SWF support

### PR DESCRIPTION
**Pull request by georgeionita**
* Implemented signal_workflow_execution for SWF
* Wired SWF backend to the moto server
* Fixed incorrect handling of task list parameter on start_workflow_execution

### CODE REVIEW

**Comment by georgeionita** [comment]
@spulec @jbbarth would you mind having a look at this and let me know if there's anything else to add/change?

**Comment by JackDanger** [comment]
@georgeionita This looks great! Welcome to Moto! :)

**Comment by jbbarth** [comment]
A little late but hey, it looks good! Thanks @georgeionita!

**Comment by georgeionita** [comment]
Thanks guys! Do you think we can get a new version so we can push the update downstream to localstack?

George
________________________________

**Comment by JackDanger** [comment]
@georgeionita Great idea, I'll compile release notes and release a new version now.

**Pull request merged**
