### PR TITLE
In SecretsManager.DescribeSecret, include VersionIdsToStages field

### PR DESCRIPTION
**Pull request by sam-clotfelter**
Implements this issue.
https://github.com/spulec/moto/issues/2230

### CODE REVIEW

**Comment by terrycain** [comment]
Add some tests to verify this behaviour

**Comment by sam-clotfelter** [comment]
Tests have been added. Sorry about that.

I found and fixed a bug from when I implemented support for multiple version secrets. AWSCURRENT was not being set correctly when put_secret_value was called on an empty secret and a custom VersionStage was passed to it.

While fixing this, I changed the data structure. version_stages has been changed from a list to a set.

**Comment by spulec** [comment]
Looks like everything is good other than the linter. If we can get that cleaned up, happy to merge!

**Comment by rolfarrestam** [comment]
This PR is exactly what I'm looking for, to be able to run local tests of my secrets rotation lambdas.
When will the extra linebreak be removed, so the merge can be made?

**Comment by spulec** [comment]
@rolfarrestam if you want to copy these changes into a new PR with the newline removed, I'll be happy to merge.

**Comment by bblommers** [comment]
Will close this, as the functionality has now been implemented in #3029.

**Pull request closed without merging**
