### PR TITLE
Check if subject_alt_names is not none before checking length

### PR DESCRIPTION
**Pull request by WhileLoop**
Calling describe_certificate was returning the following error:

   File "/usr/local/lib/python3.6/site-packages/moto/acm/responses.py", line 188, in request_certificate
    if len(subject_alt_names) > 10:
TypeError: object of type 'NoneType' has no len()

### CODE REVIEW

**Comment by JackDanger** [comment]
Thanks for this @WhileLoop! Would you be willing to try writing a test that exercises this behavior? If we'd had one already we might have avoided this bug to begin with. Whatever your code did to trigger this edge case it would be great to have as logic in the Moto test suite. Somewhere in `tests/test_acm/test_acm.py` is the right place.

**Comment by JackDanger** [comment]
If you get stuck for any reason just leave a comment here and I or somebody else will step in and help!

**Comment by WhileLoop** [comment]
@JackDanger added a simple test case.

**Comment by JackDanger** [comment]
Thanks @WhileLoop! You've just saved a bunch of other people from running into the same frustrating bug that you found. Nice work!

**Comment by JackDanger** [comment]
This is now released as Moto 1.1.24

**Pull request merged**
