### PR TITLE
Install addition package files

### PR DESCRIPTION
**Pull request by JackDanger**

### CODE REVIEW

**Comment by jonmcoe** [comment]
this will fix this bug introduced in 1.1.15 right?

```
======================================================================
ERROR: Failure: IOError ([Errno 2] No such file or directory: u'[MY_PATH]/moto/ec2/resources/instance_types.json')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "[MY_PATH]/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "[MY_PATH]/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "[MY_PATH]/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "[MY_TEST_FILE]", line 15, in <module>
    from moto import mock_s3
  File "[MY_PATH]/moto/__init__.py", line 8, in <module>
    from .acm import mock_acm  # flake8: noqa
  File "[MY_PATH]/moto/acm/__init__.py", line 2, in <module>
    from .models import acm_backends
  File "[MY_PATH]/moto/acm/models.py", line 7, in <module>
    from moto.ec2 import ec2_backends
  File "[MY_PATH]/moto/ec2/__init__.py", line 2, in <module>
    from .models import ec2_backends
  File "[MY_PATH]/moto/ec2/models.py", line 115, in <module>
    INSTANCE_TYPES = json.load(open(os.path.join(RESOURCES_DIR, 'instance_types.json'), 'r'))
IOError: [Errno 2] No such file or directory: u'[MY_PATH]/moto/ec2/resources/instance_types.json'
```

**Comment by jonmcoe** [comment]
@JackDanger

**Comment by JackDanger** [comment]
@jonmcoe correct. 1.1.19 now works

**Comment by jonmcoe** [comment]
Awesome thanks!

**Pull request merged**
